/// Complete Arabic translations for the ORBIT SMS V3 application.
const Map<String, String> ar = {
  // ---------------------------------------------------------------------------
  // Common
  // ---------------------------------------------------------------------------
  'appName': 'اوربت SMS',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  'success': 'تمت العملية بنجاح',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'delete': 'حذف',
  'edit': 'تعديل',
  'save': 'حفظ',
  'search': 'بحث',
  'filter': 'تصفية',
  'export': 'تصدير',
  'import': 'استيراد',
  'refresh': 'تحديث',
  'retry': 'إعادة المحاولة',
  'close': 'إغلاق',
  'back': 'رجوع',
  'next': 'التالي',
  'previous': 'السابق',
  'seeAll': 'عرض الكل',
  'noData': 'لا توجد بيانات',
  'noResults': 'لا توجد نتائج',
  'yes': 'نعم',
  'no': 'لا',
  'ok': 'حسناً',
  'done': 'تم',
  'select': 'اختيار',
  'selectAll': 'تحديد الكل',
  'deselectAll': 'إلغاء تحديد الكل',
  'copy': 'نسخ',
  'copied': 'تم النسخ',
  'share': 'مشاركة',
  'download': 'تحميل',
  'upload': 'رفع',
  'add': 'إضافة',
  'remove': 'إزالة',
  'apply': 'تطبيق',
  'reset': 'إعادة تعيين',
  'submit': 'إرسال',
  'continue_': 'متابعة',
  'skip': 'تخطي',
  'details': 'التفاصيل',
  'more': 'المزيد',
  'less': 'أقل',
  'all': 'الكل',
  'active': 'نشط',
  'inactive': 'غير نشط',
  'enabled': 'مفعّل',
  'disabled': 'معطّل',
  'pending': 'قيد الانتظار',
  'completed': 'مكتمل',
  'failed': 'فشل',
  'sent': 'مُرسل',
  'delivered': 'تم التوصيل',
  'rejected': 'مرفوض',
  'from': 'من',
  'to': 'إلى',
  'date': 'التاريخ',
  'time': 'الوقت',
  'status': 'الحالة',
  'type': 'النوع',
  'count': 'العدد',
  'total': 'الإجمالي',
  'description': 'الوصف',
  'note': 'ملاحظة',
  'notes': 'ملاحظات',

  // ---------------------------------------------------------------------------
  // Auth
  // ---------------------------------------------------------------------------
  'login': 'تسجيل الدخول',
  'register': 'تسجيل حساب جديد',
  'logout': 'تسجيل الخروج',
  'username': 'اسم المستخدم',
  'password': 'كلمة المرور',
  'currentPassword': 'كلمة المرور الحالية',
  'newPassword': 'كلمة المرور الجديدة',
  'confirmPassword': 'تأكيد كلمة المرور',
  'phone': 'رقم الجوال',
  'email': 'البريد الإلكتروني',
  'forgotPassword': 'نسيت كلمة المرور؟',
  'resetPassword': 'إعادة تعيين كلمة المرور',
  'otpVerification': 'التحقق من رمز OTP',
  'verify': 'تحقق',
  'resendCode': 'إعادة إرسال الرمز',
  'codeExpiresIn': 'ينتهي الرمز خلال',
  'rememberMe': 'تذكرني',
  'termsAndConditions': 'الشروط والأحكام',
  'privacyPolicy': 'سياسة الخصوصية',
  'createAccount': 'إنشاء حساب',
  'welcomeBack': 'مرحباً بعودتك',
  'signInToContinue': 'سجّل الدخول للمتابعة',
  'enterOtpSent': 'أدخل رمز التحقق المرسل إلى',
  'agreeToTerms': 'بالتسجيل أنت توافق على',
  'and': 'و',
  'alreadyHaveAccount': 'لديك حساب بالفعل؟',
  'dontHaveAccount': 'ليس لديك حساب؟',
  'fullName': 'الاسم الكامل',
  'companyName': 'اسم الشركة',
  'changePassword': 'تغيير كلمة المرور',
  'passwordChanged': 'تم تغيير كلمة المرور بنجاح',

  // ---------------------------------------------------------------------------
  // Dashboard
  // ---------------------------------------------------------------------------
  'dashboard': 'لوحة التحكم',
  'currentBalance': 'الرصيد الحالي',
  'messagesUnit': 'رسالة',
  'services': 'الخدمات',
  'consumedPoints': 'النقاط المستهلكة',
  'viewAllOperations': 'عرض كل العمليات',
  'newMessage': 'رسالة جديدة',
  'advancedSend': 'إرسال متقدم',
  'groups': 'المجموعات',
  'subAccounts': 'الحسابات الفرعية',
  'addBalance': 'إضافة رصيد',
  'quickActions': 'إجراءات سريعة',
  'recentOperations': 'العمليات الأخيرة',
  'sendingStatistics': 'إحصائيات الإرسال',
  'todaySent': 'مُرسل اليوم',
  'monthSent': 'مُرسل هذا الشهر',
  'totalSent': 'إجمالي المُرسل',
  'dashboardWelcomeDesc': 'مرحباً بك في لوحة تحكم اوربت SMS، يمكنك إدارة حسابك وإرسال رسائلك بكل سهولة',
  'accountStats': 'إحصائيات الحساب',
  'viewAllServices': 'عرض جميع الخدمات',
  'manageGroups': 'إدارة المجموعات',
  'manageAccounts': 'إدارة الحسابات',
  'groupUnit': 'مجموعة',
  'accountUnit': 'حساب',
  'buyNewBalance': 'شراء رصيد جديد',
  'sendingReports': 'تقارير الإرسال',
  'loadingDataError': 'حدث خطأ في تحميل البيانات',
  'selectMessageType': 'اختر نوع الرسالة',
  'normalSms': 'رسائل عادية',
  'normalSmsDesc': 'إرسال رسائل نصية قصيرة',
  'groupSms': 'رسائل للمجموعات',
  'groupSmsDesc': 'إرسال رسائل لمجموعات جهات الاتصال',
  'longSms': 'رسائل طويلة',
  'longSmsDesc': 'إرسال رسائل نصية طويلة',
  'voiceSms': 'رسائل صوتية',
  'voiceSmsDesc': 'إرسال رسائل صوتية مسجلة',
  'fileSms': 'رسائل ملف',
  'fileSmsDesc': 'إرسال رسائل مع ملفات مرفقة',
  'recentMessages': 'أحدث الرسائل',
  'unknown': 'غير معروف',
  'statusSent_': 'مرسلة',
  'statusDelivered_': 'تم التسليم',
  'statusRejected_': 'مرفوضة',
  'statusFailed_': 'فشلت',
  'statusPending__': 'قيد الانتظار',
  'statusScheduled_': 'مجدولة',
  'statusCancelled_': 'ملغاة',
  'statusExpired__': 'منتهية',
  'upgradeToLevel': 'للترقية إلى "{level}"، يجب شحن رصيد بقيمة {amount} ريال',
  'bannerWelcomeTitle': 'مرحبا بك في اوربت SMS',
  'bannerWelcomeDesc': 'ارسل رسائلك بكل سهولة وسرعة',
  'bannerOffersTitle': 'عروض حصرية',
  'bannerOffersDesc': 'احصل على خصومات تصل الى 30%',
  'tier_diamond': 'الماسي',
  'tier_gold': 'الذهبي',
  'tier_silver': 'الفضي',
  'tier_bronze': 'البرونزي',
  'tier_basic': 'اساسي',
  'langToggleAr': 'عر',

  // ---------------------------------------------------------------------------
  // Messages
  // ---------------------------------------------------------------------------
  'messageCenter': 'مركز الرسائل',
  'sendMessage': 'إرسال رسالة',
  'sendToNumbers': 'إرسال إلى أرقام',
  'sendToGroups': 'إرسال إلى مجموعات',
  'senderName': 'اسم المرسل',
  'messageBody': 'نص الرسالة',
  'sendNow': 'إرسال الآن',
  'schedule': 'جدولة',
  'scheduleMessage': 'جدولة الرسالة',
  'scheduledDate': 'تاريخ الجدولة',
  'scheduledTime': 'وقت الجدولة',
  'preview': 'معاينة',
  'messageCost': 'تكلفة الرسالة',
  'recipientsCount': 'عدد المستقبلين',
  'smsCount': 'عدد الرسائل',
  'template': 'قالب',
  'selectTemplate': 'اختر قالب',
  'saveAsTemplate': 'حفظ كقالب',
  'messageType': 'نوع الرسالة',
  'characters': 'حرف',
  'remainingCharacters': 'الأحرف المتبقية',
  'enterNumbers': 'أدخل الأرقام',
  'numbersHint': 'أدخل الأرقام مفصولة بسطر جديد',
  'selectSenderName': 'اختر اسم المرسل',
  'messagePreview': 'معاينة الرسالة',
  'confirmSend': 'تأكيد الإرسال',
  'messageSent': 'تم إرسال الرسالة بنجاح',
  'messageScheduled': 'تمت جدولة الرسالة بنجاح',
  'duplicateNumbers': 'أرقام مكررة',
  'invalidNumbers': 'أرقام غير صالحة',
  'removeDuplicates': 'إزالة المكرر',
  'removeInvalid': 'إزالة غير الصالح',

  // ---------------------------------------------------------------------------
  // Groups
  // ---------------------------------------------------------------------------
  'createGroup': 'إنشاء مجموعة',
  'editGroup': 'تعديل المجموعة',
  'deleteGroup': 'حذف المجموعة',
  'groupName': 'اسم المجموعة',
  'numbers': 'الأرقام',
  'addNumber': 'إضافة رقم',
  'importExcel': 'استيراد من Excel',
  'phoneNumber': 'رقم الهاتف',
  'name': 'الاسم',
  'identifier': 'المعرّف',
  'contactsCount': 'عدد جهات الاتصال',
  'addContact': 'إضافة جهة اتصال',
  'editContact': 'تعديل جهة اتصال',
  'deleteContact': 'حذف جهة اتصال',
  'importContacts': 'استيراد جهات اتصال',
  'exportContacts': 'تصدير جهات اتصال',
  'groupCreated': 'تم إنشاء المجموعة بنجاح',
  'groupUpdated': 'تم تحديث المجموعة بنجاح',
  'groupDeleted': 'تم حذف المجموعة بنجاح',
  'contactAdded': 'تمت إضافة جهة الاتصال بنجاح',
  'contactUpdated': 'تم تحديث جهة الاتصال بنجاح',
  'contactDeleted': 'تم حذف جهة الاتصال بنجاح',
  'confirmDeleteGroup': 'هل أنت متأكد من حذف هذه المجموعة؟',
  'confirmDeleteContact': 'هل أنت متأكد من حذف جهة الاتصال هذه؟',
  'noGroups': 'لا توجد مجموعات',
  'noContacts': 'لا توجد جهات اتصال',
  'searchContacts': 'بحث في جهات الاتصال',
  'searchGroups': 'بحث عن مجموعة...',
  'showTrashed': 'عرض المحذوفة',
  'numberUnit': 'رقم',
  'startCreatingGroup': 'ابدأ بإنشاء مجموعة جديدة لتنظيم أرقامك',
  'exportingGroups': 'جاري تصدير المجموعات...',
  'exportFailed': 'فشل التصدير',
  'groupNameUpdated': 'تم تحديث الاسم بنجاح',
  'groupNameUpdateFailed': 'فشل تحديث الاسم',
  'groupRestored': 'تم استعادة المجموعة',
  'confirmDeleteGroupNamed': 'هل أنت متأكد من حذف المجموعة',
  'editGroupName': 'تعديل اسم المجموعة',
  'addNumbers': 'إضافة أرقام',
  'addNumberManual': 'إضافة رقم يدوي',
  'addNumberManualSubtitle': 'أدخل الاسم ورقم الهاتف يدوياً',
  'addFromContacts': 'إضف من جهات الاتصال',
  'addFromContactsSubtitle': 'استيرد أرقام جوال سعودية من جهازك',
  'numberUpdated': 'تم تحديث الرقم',
  'numberAdded': 'تمت الإضافة بنجاح',
  'deleteNumber': 'حذف الرقم',
  'confirmDeleteNumber': 'هل أنت متأكد من حذف',
  'numberDeleted': 'تم حذف الرقم',
  'noNumbers': 'لا توجد أرقام',
  'addNumbersOrImport': 'أضف أرقاماً لهذه المجموعة أو استوردها من ملف Excel',
  'exporting': 'جاري التصدير...',
  'trashed': 'محذوف',
  'createNewGroup': 'إنشاء مجموعة جديدة',
  'enterGroupName': 'أدخل اسم المجموعة',
  'groupNameRequired': 'اسم المجموعة مطلوب',
  'groupNameMinLength': 'اسم المجموعة يجب أن يكون حرفين على الأقل',
  'createGroupButton': 'إنشاء المجموعة',
  'addNumbersAfterCreate': 'يمكنك إضافة أرقام للمجموعة بعد إنشائها',
  'unexpectedError': 'حدث خطأ غير متوقع',
  'editNumber': 'تعديل رقم',
  'addNewNumber': 'إضافة رقم جديد',
  'contactNameLabel': 'الاسم',
  'enterContactName': 'أدخل اسم الجهة الاتصال',
  'phoneNumberRequired': 'رقم الهاتف مطلوب',
  'identifierOptional': 'المعرف (اختياري)',
  'identifierHint': 'رقم الهوية أو رقم الموظف',
  'update': 'تحديث',
  'importNumbers': 'استيراد أرقام',
  'standardImport': 'استيراد عادي',
  'customImport': 'استيراد مخصص',
  'contactsTab': 'جهات الاتصال',
  'standardImportInfo': 'الحد الأقصى 5000 سطر. الملف يجب أن يحتوي على أعمدة: الاسم، رقم الهاتف',
  'customImportInfo': 'حدد أعمدة الملف لربطها بالحقول المطلوبة',
  'contactsImportInfo': 'اختر جهات اتصال من جهازك لاستيرادها إلى المجموعة',
  'phoneColumnRequired': 'عمود رقم الهاتف مطلوب',
  'groupColumnRequired': 'عمود المجموعة مطلوب',
  'contactsPermissionRequired': 'يجب السماح بالوصول إلى جهات الاتصال',
  'contactsReadError': 'خطأ في قراءة جهات الاتصال',
  'importFileError': 'خطأ في إنشاء ملف الاستيراد',
  'uploadFileButton': 'رفع الملف',
  'phoneColumnLabel': 'عمود رقم الهاتف *',
  'phoneColumnHint': 'مثال: A أو phone',
  'nameColumnLabel': 'عمود الاسم (اختياري)',
  'nameColumnHint': 'مثال: B أو name',
  'identifierColumnLabel': 'عمود المعرف (اختياري)',
  'identifierColumnHint': 'مثال: C أو identifier',
  'groupColumnLabel': 'عمود المجموعة *',
  'groupColumnHint': 'مثال: D أو group',
  'selectedContactsCount': 'تم اختيار {count} جهة اتصال',
  'tapToSelectContacts': 'اضغط لاختيار جهات الاتصال',
  'tapToEditSelection': 'اضغط لتعديل الاختيار',
  'importContactsCount': 'استيراد {count} جهة اتصال',
  'tapToSelectExcel': 'اضغط لاختيار ملف Excel',
  'supportedFormats': 'الصيغ المدعومة: xlsx, xls, csv',
  'importCompleted': 'اكتمل الاستيراد',
  'importSuccessful': 'ناجح',
  'importFailed': 'فاشل',
  'importAnother': 'استيراد آخر',
  'selectContactsTitle': 'اختر جهات الاتصال',
  'confirmCount': 'تأكيد ({count})',
  'uploadFailedRetry': 'فشل الرفع. حاول مرة أخرى.',
  'addFromContactsTitle': 'إضافة من جهات الاتصال',
  'saudiNumbersOnlyInfo': 'سيتم إضافة أرقام الجوال السعودية فقط بجميع صيغها (05xx, +966xx, 966xx)',
  'importAllContacts': 'إضافة جميع جهات الاتصال',
  'importAllContactsSubtitle': 'سحب كل أرقام الجوال السعودية من جهازك',
  'selectSpecificContacts': 'اختيار جهات اتصال محددة',
  'selectSpecificContactsSubtitle': 'اختر الأرقام التي تريد إضافتها',
  'addingContacts': 'جاري إضافة جهات الاتصال...',
  'screenWontSleep': 'الشاشة لن تنطفئ حتى يكتمل الاستيراد',
  'additionCompleted': 'اكتملت الإضافة',
  'addedSuccessfully': 'تمت إضافته',
  'nonSaudi': 'غير سعودي',
  'alreadyExists': 'موجود بالفعل',
  'contactsAddError': 'خطأ في إضافة جهات الاتصال',
  'noSaudiNumbers': 'لا توجد أرقام جوال سعودية في جهات الاتصال',
  'selectNumbers': 'اختر الأرقام',
  'searchByNameOrNumber': 'بحث بالاسم أو الرقم...',
  'deselectAllFiltered': 'إلغاء الكل',
  'saudiNumberCount': '{count} رقم سعودي',
  'nonSaudiSkipped': '{count} غير سعودي (تم تجاوزه)',
  'noName': 'بدون اسم',
  'addCount': 'إضافة ({count})',

  // ---------------------------------------------------------------------------
  // Balance
  // ---------------------------------------------------------------------------
  'balance': 'الرصيد',
  'buyBalance': 'شراء رصيد',
  'transferBalance': 'تحويل رصيد',
  'transactionHistory': 'سجل المعاملات',
  'bankTransfer': 'تحويل بنكي',
  'onlinePayment': 'دفع إلكتروني',
  'stcPay': 'STC Pay',
  'sadad': 'سداد',
  'amount': 'المبلغ',
  'pricePerSms': 'سعر الرسالة',
  'vat': 'ضريبة القيمة المضافة',
  'totalAmount': 'المبلغ الإجمالي',
  'paymentMethod': 'طريقة الدفع',
  'paymentSuccess': 'تمت عملية الدفع بنجاح',
  'paymentFailed': 'فشلت عملية الدفع',
  'transferTo': 'تحويل إلى',
  'transferFrom': 'تحويل من',
  'transferAmount': 'مبلغ التحويل',
  'transferSuccess': 'تم التحويل بنجاح',
  'noTransactions': 'لا توجد معاملات',
  'invoiceNumber': 'رقم الفاتورة',
  'balancePackages': 'باقات الرصيد',
  'customAmount': 'مبلغ مخصص',
  'minimumAmount': 'الحد الأدنى للمبلغ',
  'maximumAmount': 'الحد الأقصى للمبلغ',
  'sar': 'ر.س',

  // Balance Tabs
  'balanceLog': 'سجل الرصيد',
  'packages': 'الباقات',
  'bankInfo': 'معلومات البنك',
  'upgradeJourney': 'رحلة الترقية',
  'requestContractProof': 'طلب إثبات تعاقد',
  'balanceTotal': 'الإجمالي',
  'balanceRemaining': 'المتبقي',
  'balanceConsumed': 'المستهلك',
  'balanceTransferred': 'تم تحويله',
  'balanceExpiresIn': 'سينتهي الرصيد خلال',
  'day': 'يوم',
  'hour': 'ساعة',
  'minute': 'دقيقة',
  'second': 'ثانية',
  'availablePackages': 'الباقات المتاحة',
  'choosePackage': 'اختر الباقة المناسبة لاحتياجاتك',
  'noPackages': 'لا توجد باقات متاحة',
  'buy': 'شراء',
  'bankInfoTitle': 'معلومات البنك',
  'bankInfoSubtitle': 'يمكنك التحويل إلى أحد الحسابات التالية',
  'noBankInfo': 'لا توجد معلومات بنكية',
  'accountName': 'اسم الحساب',
  'accountNumber': 'رقم الحساب',
  'transferToSubAccount': 'تحويل رصيد إلى حساب فرعي',
  'transferHistory': 'سجل التحويلات',
  'noTransferHistory': 'لا توجد تحويلات سابقة',
  'currentLevel': 'مستواك الحالي',
  'progressToNextLevel': 'التقدم نحو المستوى التالي',
  'upgradeLevels': 'مستويات الترقية',
  'current': 'حالي',
  'messagesNeeded': 'رسالة إضافية للوصول إلى المستوى',
  'levelBasic': 'أساسي',
  'levelSilver': 'فضي',
  'levelGold': 'ذهبي',
  'levelPlatinum': 'بلاتيني',
  'levelDiamond': 'ماسي',
  'exportData': 'سيتم تصدير البيانات قريباً',
  'searchLog': 'بحث في السجل...',
  'accepted': 'مقبولة',
  'expired': 'منتهي',

  // Balance Screen - additional keys
  'currentBalanceLabel': 'رصيدك الحالي',
  'availableMessages': 'رسالة متاحة',
  'expiryDate': 'تاريخ الانتهاء',
  'remainingDaysLabel': 'يوم متبقي',
  'transactions': 'العمليات',
  'filterByDateBalance': 'فلتر بالتاريخ',
  'searchTransactions': 'بحث في العمليات...',
  'transactionCount': 'عملية',
  'noTransactionsFound': 'لا توجد عمليات',
  'noTransactionsMatchFound': 'لم يتم العثور على عمليات مطابقة',
  'statusPending': 'قيد الانتظار',
  'statusApproved': 'موافق عليه',
  'statusWaiting': 'بانتظار المراجعة',
  'onlinePaymentNoon': 'دفع إلكتروني Noon',
  'bankTransferRemittance': 'حوالة مصرفية',
  'amountSar': 'المبلغ (ر.س)',
  'enterAmountSar': 'أدخل المبلغ بالريال السعودي',
  'amountRequired': 'المبلغ مطلوب',
  'enterValidAmount': 'أدخل مبلغاً صحيحاً',
  'baseAmount': 'المبلغ الأساسي',
  'taxAmount': 'الضريبة (15%)',
  'smsCountLabel': 'عدد الرسائل',
  'messageUnit': 'رسالة',
  'confirmPurchase': 'تأكيد الشراء',
  'priceTable': 'جدول الأسعار',
  'quantity': 'الكمية',
  'selectBank': 'اختر البنك',
  'depositorName': 'اسم المودع',
  'depositorNameHint': 'اسم صاحب الحوالة',
  'depositorNameRequired': 'اسم المودع مطلوب',
  'transferDateLabel': 'تاريخ التحويل',
  'selectDateLabel': 'اختر التاريخ',
  'transferDateRequired': 'تاريخ التحويل مطلوب',
  'receiptOptional': 'إيصال التحويل (اختياري)',
  'tapToUploadReceipt': 'اضغط لرفع الإيصال',
  'phoneStcPay': 'رقم الهاتف (STC Pay)',
  'phoneRequired': 'رقم الهاتف مطلوب',
  'nationalId': 'رقم الهوية الوطنية',
  'enterNationalId': 'أدخل رقم الهوية',
  'nationalIdRequired': 'رقم الهوية مطلوب',
  'otpSentStcPay': 'تم إرسال رمز التحقق إلى هاتفك عبر STC Pay',
  'otpCode': 'رمز التحقق',
  'enterOtpCode': 'أدخل الرمز المرسل',
  'confirmOtp': 'تأكيد الرمز',
  'purchaseSuccess': 'تم الشراء بنجاح',
  'purchaseRequestSent': 'تم إرسال طلب الشراء بنجاح',
  'selectBankRequired': 'يرجى اختيار البنك',
  'otpSentInfo': 'تم إرسال رمز التحقق',
  'sadadInvoiceCreated': 'تم إنشاء فاتورة سداد',
  'invoiceNumberLabel': 'رقم الفاتورة:',
  'validUntil': 'صالحة حتى:',
  'payViaBankOrAtm': 'يمكنك الدفع عبر تطبيق البنك أو أجهزة الصراف',
  'confirmTransfer': 'تأكيد التحويل',
  'recipientPhone': 'رقم الهاتف المستلم',
  'enterCount': 'أدخل العدد',
  'countRequired': 'العدد مطلوب',
  'enterValidCount': 'أدخل عدداً صحيحاً',
  'transferButton': 'تحويل',
  'noPreviousTransfers': 'لا توجد تحويلات سابقة',
  'bankInfoNotAdded': 'لم يتم إضافة معلومات بنكية بعد',
  'copiedLabel': 'تم نسخ',
  'copyTooltip': 'نسخ',
  'noPackagesCurrently': 'لا توجد باقات رسائل متاحة حالياً',
  'popular': 'مميز',
  'additionalAddons': 'إضافي',
  'smsPrice': 'سعر الرسالة:',
  'transferConfirmMessage': 'هل تريد تحويل {amount} رسالة إلى الرقم {phone}؟',
  'needAdditionalMessages': 'تحتاج {count} رسالة إضافية للوصول إلى المستوى {level}',
  'fromMessages': 'من {count} رسالة',

  // Notifications - additional keys
  'deleteNotification': 'حذف الإشعار',
  'confirmDeleteNotification': 'هل أنت متأكد من حذف هذا الإشعار؟',
  'notificationDeleted': 'تم حذف الإشعار',
  'exportingData': 'جاري تصدير البيانات',
  'searchNotifications': 'بحث في الإشعارات...',
  'sendNotificationTitle': 'إرسال إشعار',
  'sendButton': 'إرسال',
  'noNotificationsFound': 'لا توجد إشعارات',
  'sendInstantNotifications': 'أرسل إشعارات فورية لعملائك',
  'sendNotificationAction': 'إرسال إشعار',
  'recipientNumbers': 'أرقام المستلمين',
  'enterNumbersSeparated': 'أدخل الأرقام مفصولة بفاصلة',
  'enterAtLeastOneNumber': 'يرجى إدخال رقم واحد على الأقل',
  'notificationText': 'نص الإشعار',
  'enterNotificationText': 'أدخل نص الإشعار',
  'notificationTextRequired': 'يرجى إدخال نص الإشعار',
  'notificationSentSuccess': 'تم إرسال الإشعار بنجاح',
  'recipientCountPreview': 'عدد المستلمين',
  'estimatedCost': 'التكلفة التقديرية',
  'notifStatusSent': 'مرسل',
  'notifStatusFailed': 'فشل',
  'notifStatusPending': 'قيد الانتظار',
  'recipientLabel': 'مستلم',

  // ---------------------------------------------------------------------------
  // Archive
  // ---------------------------------------------------------------------------
  'archive': 'الأرشيف',
  'archivedMessages': 'الرسائل المؤرشفة',
  'sender': 'المرسل',
  'recipient': 'المستقبل',
  'message': 'الرسالة',
  'filterByDate': 'تصفية حسب التاريخ',
  'filterBySender': 'تصفية حسب المرسل',
  'filterByStatus': 'تصفية حسب الحالة',
  'cancelPending': 'إلغاء المعلّقة',
  'restore': 'استعادة',
  'startDate': 'تاريخ البداية',
  'endDate': 'تاريخ النهاية',
  'noMessages': 'لا توجد رسائل',
  'messageDetails': 'تفاصيل الرسالة',
  'deliveryReport': 'تقرير التسليم',

  // Archive Types
  'archive_type_general': 'الأرشيف العام',
  'archive_type_custom_messages': 'الرسائل المخصصة',
  'archive_type_absence_lateness': 'الغياب والتأخر',
  'archive_type_teacher_messages': 'رسائل المعلمين',
  'archive_type_long_messages': 'الرسائل الطويلة',
  'archive_type_voice_messages': 'الرسائل الصوتية',
  'archive_type_file_messages': 'رسائل الملفات',
  'archive_type_thanks_certifications': 'شهادات الشكر',
  'archive_type_vip_cards': 'بطاقات VIP',
  'archive_type_bulk_messages': 'الرسائل الجماعية',

  // Archive Send At Filter
  'archive_send_at_all': 'الكل',
  'archive_send_at_now': 'فوري',
  'archive_send_at_later': 'مجدول',
  'archive_send_at_api': 'عبر API',

  // Archive Message Status
  'archive_status_sent': 'مرسلة',
  'archive_status_delivered': 'تم التسليم',
  'archive_status_pending': 'قيد الانتظار',
  'archive_status_failed': 'فشلت',
  'archive_status_rejected': 'مرفوضة',
  'archive_status_scheduled': 'مجدولة',
  'archive_status_cancelled': 'ملغاة',
  'archive_status_expired': 'منتهية',
  'archive_status_unknown': 'غير معروف',

  // Archive Screen UI
  'archive_filter_title': 'تصفية الأرشيف',
  'archive_send_type': 'نوع الإرسال',
  'archive_date_range': 'الفترة الزمنية',
  'archive_phone_number': 'رقم الهاتف',
  'archive_enter_phone': 'أدخل رقم الهاتف',
  'archive_reset_filters': 'إعادة ضبط',
  'archive_search_hint': 'بحث في الأرشيف...',
  'archive_delete_messages': 'حذف الرسائل',
  'archive_confirm_delete': 'هل أنت متأكد من حذف {count} رسالة؟',
  'archive_messages_deleted': 'تم حذف الرسائل بنجاح',
  'archive_cancel_messages': 'إلغاء الرسائل',
  'archive_confirm_cancel': 'هل أنت متأكد من إلغاء {count} رسالة معلقة؟',
  'archive_messages_cancelled': 'تم إلغاء الرسائل بنجاح',
  'archive_messages_restored': 'تم استعادة الرسائل بنجاح',
  'archive_export_requested': 'تم طلب التصدير بنجاح',
  'archive_no_messages_in': 'لا توجد رسائل في هذا القسم',
  'archive_delete_failed': 'فشل حذف الرسائل',
  'archive_cancel_pending_failed': 'فشل إلغاء الرسائل',
  'archive_cancel_pending_success': 'تم إلغاء الرسائل المعلقة بنجاح',
  'archive_restore_failed': 'فشل استعادة الرسائل',

  // ---------------------------------------------------------------------------
  // Settings
  // ---------------------------------------------------------------------------
  'settings': 'الإعدادات',
  'profile': 'الملف الشخصي',
  'roles': 'الأدوار',
  'permissions': 'الصلاحيات',
  'invoices': 'الفواتير',
  'apiKeys': 'مفاتيح API',
  'senderNames': 'أسماء المرسلين',
  'contracts': 'العقود',
  'balanceReminder': 'تنبيه الرصيد',
  'help': 'المساعدة',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'الإنجليزية',
  'theme': 'المظهر',
  'lightMode': 'الوضع الفاتح',
  'darkMode': 'الوضع الداكن',
  'systemMode': 'وضع النظام',
  'notifications': 'الإشعارات',
  'notificationSettings': 'إعدادات الإشعارات',
  'enableNotifications': 'تفعيل الإشعارات',
  'notificationSound': 'صوت الإشعار',
  'notificationVibration': 'اهتزاز الإشعار',
  'about': 'حول التطبيق',
  'version': 'الإصدار',
  'termsOfService': 'شروط الخدمة',
  'contactUs': 'تواصل معنا',
  'rateApp': 'قيّم التطبيق',
  'shareApp': 'شارك التطبيق',
  'editProfile': 'تعديل الملف الشخصي',
  'profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
  'deleteAccount': 'حذف الحساب',
  'confirmLogout': 'هل أنت متأكد من تسجيل الخروج؟',
  'confirmDeleteAccount': 'هل أنت متأكد من حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
  'minimumBalanceAlert': 'تنبيه عند وصول الرصيد إلى',
  'addSenderName': 'إضافة اسم مرسل',
  'senderNameStatus': 'حالة اسم المرسل',
  'apiKeyGenerated': 'تم إنشاء مفتاح API بنجاح',
  'generateApiKey': 'إنشاء مفتاح API',
  'copyApiKey': 'نسخ مفتاح API',

  // ---------------------------------------------------------------------------
  // Settings - Status Labels
  // ---------------------------------------------------------------------------
  'invoice_status_paid': 'مدفوعة',
  'invoice_status_unpaid': 'غير مدفوعة',
  'invoice_status_pending': 'قيد الانتظار',
  'invoice_status_overdue': 'متأخرة',
  'invoice_status_cancelled': 'ملغاة',
  'invoice_status_refunded': 'مستردة',
  'invoice_status_unknown': 'غير محدد',
  'contract_status_active': 'نشط',
  'contract_status_inactive': 'غير نشط',
  'contract_status_pending': 'قيد المراجعة',
  'contract_status_expired': 'منتهي',
  'contract_status_cancelled': 'ملغي',
  'contract_status_unknown': 'غير محدد',
  'sender_status_pending': 'قيد المراجعة',
  'sender_status_approved': 'مقبول',
  'sender_status_rejected': 'مرفوض',
  'sender_status_active': 'نشط',
  'sender_status_inactive': 'غير نشط',
  'sender_status_payment_pending': 'بانتظار الدفع',
  'sender_status_unknown': 'غير محدد',
  'permission_group_general': 'عام',

  // ---------------------------------------------------------------------------
  // Settings - Screens
  // ---------------------------------------------------------------------------
  'settings_section_account': 'الحساب',
  'settings_profile_subtitle': 'تعديل البيانات الشخصية',
  'settings_change_password_subtitle': 'تحديث كلمة المرور الحالية',
  'settings_section_management': 'الإدارة',
  'settings_sub_accounts_subtitle': 'إدارة المستخدمين الفرعيين',
  'settings_roles_title': 'الأدوار والصلاحيات',
  'settings_roles_subtitle': 'إدارة أدوار المستخدمين',
  'settings_section_financial': 'المالية',
  'settings_invoices_subtitle': 'عرض وتحميل الفواتير',
  'settings_balance_reminder_subtitle': 'إعدادات التنبيه عند انخفاض الرصيد',
  'settings_section_technical': 'التقنية',
  'settings_api_keys_subtitle': 'إدارة مفاتيح الوصول للواجهة البرمجية',
  'settings_section_senders': 'المرسلين',
  'settings_sender_names_subtitle': 'طلب وإدارة أسماء المرسلين',
  'settings_contracts_subtitle': 'إدارة العقود والمستندات',
  'settings_user_default': 'المستخدم',
  'settings_balance_reminder_desc': 'سيتم تنبيهك عندما ينخفض رصيدك عن الحد المحدد.',
  'settings_enable_reminder': 'تفعيل التنبيه',
  'settings_min_balance': 'الحد الأدنى للرصيد',
  'settings_min_balance_hint': 'مثال: 100',
  'settings_reminder_saved': 'تم حفظ إعدادات التنبيه بنجاح',
  'settings_reminder_save_error': 'حدث خطأ أثناء الحفظ',
  'invoices_no_invoices': 'لا توجد فواتير',
  'invoices_no_match': 'لا توجد فواتير مطابقة للبحث',
  'invoices_download_error': 'لا يمكن تحميل الفاتورة',
  'invoices_invoice_prefix': 'فاتورة',
  'invoices_download_pdf': 'تحميل PDF',
  'invoices_invoice_number': 'رقم الفاتورة',
  'invoices_invoice_date': 'التاريخ',
  'invoices_invoice_status': 'الحالة',
  'invoices_invoice_amount': 'المبلغ',
  'invoices_invoice_tax': 'الضريبة',
  'invoices_invoice_total': 'الإجمالي',
  'invoices_payment_method': 'طريقة الدفع',
  'invoices_notes': 'ملاحظات',
  'invoices_items': 'البنود',
  'password_strength_weak': 'ضعيفة',
  'password_strength_medium': 'متوسطة',
  'password_strength_good': 'جيدة',
  'password_strength_strong': 'قوية',
  'password_choose_strong': 'تأكد من اختيار كلمة مرور قوية',
  'password_current_label': 'كلمة المرور الحالية',
  'password_current_hint': 'أدخل كلمة المرور الحالية',
  'password_new_label': 'كلمة المرور الجديدة',
  'password_new_hint': 'أدخل كلمة المرور الجديدة',
  'password_confirm_label': 'تأكيد كلمة المرور',
  'password_confirm_hint': 'أعد إدخال كلمة المرور الجديدة',
  'password_req_min_chars': '8 أحرف على الأقل',
  'password_req_uppercase': 'حرف كبير واحد',
  'password_req_lowercase': 'حرف صغير واحد',
  'password_req_digit': 'رقم واحد على الأقل',
  'password_req_special': 'رمز خاص واحد',
  'password_changed_success': 'تم تغيير كلمة المرور بنجاح',
  'profile_name_label': 'الاسم',
  'profile_name_hint': 'أدخل اسمك الكامل',
  'profile_email_label': 'البريد الإلكتروني',
  'profile_phone_label': 'رقم الجوال',
  'profile_landphone_label': 'رقم الهاتف الثابت',
  'profile_optional': 'اختياري',
  'profile_gender': 'الجنس',
  'profile_gender_select': 'اختر الجنس',
  'profile_gender_male': 'ذكر',
  'profile_gender_female': 'أنثى',
  'profile_org_name': 'اسم المنظمة',
  'profile_save_changes': 'حفظ التغييرات',
  'profile_camera': 'الكاميرا',
  'profile_gallery': 'المعرض',
  'profile_delete_photo': 'حذف الصورة',
  'profile_photo_updated': 'تم تحديث الصورة بنجاح',
  'profile_photo_update_failed': 'فشل تحديث الصورة',
  'profile_photo_deleted': 'تم حذف الصورة بنجاح',
  'profile_photo_delete_failed': 'فشل حذف الصورة',
  'profile_updated': 'تم تحديث الملف الشخصي بنجاح',
  'profile_update_failed': 'فشل تحديث الملف الشخصي',
  'sub_accounts_search': 'بحث في الحسابات الفرعية...',
  'sub_accounts_empty': 'لا توجد حسابات فرعية',
  'sub_accounts_empty_desc': 'اضغط على زر + لإنشاء حساب فرعي جديد',
  'sub_accounts_delete_title': 'حذف الحساب الفرعي',
  'sub_accounts_delete_confirm': 'هل أنت متأكد من حذف هذا الحساب الفرعي؟',
  'sub_accounts_deleted': 'تم حذف الحساب الفرعي',
  'sub_accounts_edit_title': 'تعديل الحساب الفرعي',
  'sub_accounts_create_title': 'إنشاء حساب فرعي',
  'sub_accounts_otp_sent': 'تم إرسال رمز التحقق إلى الجوال',
  'sub_accounts_otp_label': 'رمز التحقق',
  'sub_accounts_otp_hint': 'أدخل رمز التحقق',
  'sub_accounts_name_label': 'الاسم',
  'sub_accounts_name_hint': 'أدخل الاسم',
  'sub_accounts_password_label': 'كلمة المرور',
  'sub_accounts_password_hint': 'أدخل كلمة المرور',
  'sub_accounts_api_access': 'صلاحية API',
  'sub_accounts_api_access_desc': 'السماح بالوصول عبر الواجهة البرمجية',
  'sub_accounts_updated': 'تم تحديث الحساب الفرعي',
  'sub_accounts_update_failed': 'فشل التحديث',
  'sub_accounts_create_failed': 'فشل الإنشاء',
  'sub_accounts_created': 'تم إنشاء الحساب بنجاح',
  'sub_accounts_otp_invalid': 'رمز التحقق غير صحيح',
  'sub_accounts_create_btn': 'إنشاء',
  'roles_empty': 'لا توجد أدوار',
  'roles_empty_desc': 'اضغط على زر + لإنشاء دور جديد',
  'roles_delete_title': 'حذف الدور',
  'roles_delete_confirm': 'هل أنت متأكد من حذف هذا الدور؟',
  'roles_deleted': 'تم حذف الدور بنجاح',
  'roles_permission_count': 'صلاحية',
  'roles_edit_title': 'تعديل الدور',
  'roles_create_title': 'إنشاء دور جديد',
  'roles_name_label': 'اسم الدور',
  'roles_name_hint': 'مثال: مدير',
  'roles_description_label': 'الوصف',
  'roles_description_hint': 'وصف اختياري للدور',
  'roles_permissions_label': 'الصلاحيات',
  'roles_create_button': 'إنشاء الدور',
  'roles_deselect_all': 'إلغاء الكل',
  'roles_select_all': 'تحديد الكل',
  'roles_updated': 'تم تحديث الدور',
  'roles_created': 'تم إنشاء الدور',
  'sender_empty': 'لا توجد طلبات',
  'sender_empty_desc': 'اضغط على زر + لتقديم طلب اسم مرسل جديد',
  'sender_delete_title': 'حذف الطلب',
  'sender_delete_confirm': 'هل أنت متأكد من حذف طلب اسم المرسل؟',
  'sender_deleted': 'تم حذف الطلب',
  'sender_doc_uploaded': 'تم رفع المستند بنجاح',
  'sender_payment_ready': 'تم تجهيز رابط الدفع',
  'sender_upload_doc': 'رفع مستند',
  'sender_payment': 'الدفع',
  'sender_create_title': 'طلب اسم مرسل جديد',
  'sender_review_notice': 'سيتم مراجعة طلبك خلال 1-3 أيام عمل. يرجى إرفاق المستندات المطلوبة.',
  'sender_name_label': 'اسم المرسل',
  'sender_name_hint': 'مثال: MyCompany',
  'sender_org_label': 'اسم المنظمة',
  'sender_org_hint': 'الاسم الرسمي للمنظمة',
  'sender_commercial_register': 'السجل التجاري',
  'sender_authorization_letter': 'خطاب التفويض',
  'sender_submit': 'تقديم الطلب',
  'sender_upload_file': 'اضغط لرفع الملف',
  'sender_submitted': 'تم تقديم الطلب بنجاح',
  'sender_submit_failed': 'فشل تقديم الطلب',
  'contracts_empty': 'لا توجد عقود',
  'contracts_empty_desc': 'اضغط على زر + لإنشاء عقد جديد',
  'contracts_doc_uploaded': 'تم رفع المستند بنجاح',
  'contracts_delete_title': 'حذف العقد',
  'contracts_delete_confirm': 'هل أنت متأكد من حذف هذا العقد؟',
  'contracts_deleted': 'تم حذف العقد',
  'contracts_upload_doc': 'رفع مستند',
  'contracts_contract_prefix': 'عقد',
  'contracts_create_title': 'إنشاء عقد جديد',
  'contracts_org_label': 'اسم المنظمة',
  'contracts_org_hint': 'الاسم الرسمي للمنظمة',
  'contracts_notes_label': 'ملاحظات',
  'contracts_notes_hint': 'ملاحظات إضافية (اختياري)',
  'contracts_document_label': 'المستند',
  'contracts_upload_doc_btn': 'اضغط لرفع المستند',
  'contracts_create_button': 'إنشاء العقد',
  'contracts_created': 'تم إنشاء العقد بنجاح',
  'contracts_create_failed': 'فشل إنشاء العقد',
  'api_keys_empty': 'لا توجد مفاتيح API',
  'api_keys_empty_desc': 'اضغط على زر + لإنشاء مفتاح جديد',
  'api_keys_create_title': 'إنشاء مفتاح API',
  'api_keys_name_label': 'اسم المفتاح',
  'api_keys_name_hint': 'مثال: تطبيق الجوال',
  'api_keys_created': 'تم إنشاء المفتاح',
  'api_keys_save_warning': 'احفظ هذا المفتاح الآن. لن يتم عرضه مرة أخرى.',
  'api_keys_copied': 'تم نسخ المفتاح',
  'api_keys_understood': 'فهمت',
  'api_keys_no_name': 'مفتاح بدون اسم',
  'api_keys_created_at': 'تاريخ الإنشاء',
  'api_keys_delete_title': 'حذف المفتاح',
  'api_keys_delete_confirm_prefix': 'هل أنت متأكد من حذف المفتاح',
  'api_keys_delete_confirm_suffix': 'لن تتمكن من استخدامه بعد الحذف.',
  'api_keys_deleted': 'تم حذف المفتاح',
  'error_prefix': 'خطأ',
  'unknown_error': 'حدث خطأ',
  'operation_completed': 'تمت العملية',
  'verify_btn': 'تحقق',


  // ---------------------------------------------------------------------------
  // Statistics
  // ---------------------------------------------------------------------------
  'statistics': 'الإحصائيات',
  'absenceLateness': 'الغياب والتأخر',
  'customMessages': 'رسائل مخصصة',
  'teacherMessages': 'رسائل المعلمين',
  'exportReport': 'تصدير التقرير',
  'dailyStatistics': 'إحصائيات يومية',
  'weeklyStatistics': 'إحصائيات أسبوعية',
  'monthlyStatistics': 'إحصائيات شهرية',
  'yearlyStatistics': 'إحصائيات سنوية',
  'chart': 'رسم بياني',
  'table': 'جدول',
  'totalMessages': 'إجمالي الرسائل',
  'deliveredMessages': 'الرسائل المُوصلة',
  'failedMessages': 'الرسائل الفاشلة',
  'pendingMessages': 'الرسائل المعلّقة',
  'deliveryRate': 'نسبة التوصيل',

  // Statistics Types
  'stat_type_absence_lateness': 'الغياب والتأخر',
  'stat_type_custom_messages': 'الرسائل المخصصة',
  'stat_type_teacher_messages': 'رسائل المعلمين',

  // Statistics Sub-Types
  'stat_sub_all': 'الكل',
  'stat_sub_lateness': 'التأخر',
  'stat_sub_absence': 'الغياب',
  'stat_sub_academic_weakness': 'ضعف دراسي',
  'stat_sub_behavioural_offence': 'مخالفة سلوكية',
  'stat_sub_distinction': 'تميز',
  'stat_sub_others': 'أخرى',
  'stat_sub_guidance': 'إرشاد',
  'stat_sub_note': 'ملاحظة',

  // Statistics Screen UI
  'stat_no_statistics': 'لا توجد إحصائيات',
  'stat_no_data_in': 'لا توجد بيانات في هذا القسم',
  'stat_total_results': 'إجمالي النتائج: {count}',
  'stat_page_info': 'صفحة {current}/{last}',
  'stat_select_period': 'اختر الفترة',
  'stat_export_requested': 'تم طلب التصدير بنجاح',
  'stat_student_number': 'رقم الطالب',
  'stat_teacher': 'المعلم',
  'stat_semester': 'الفصل',
  'stat_semester_first': 'الفصل الأول',
  'stat_semester_second': 'الفصل الثاني',
  'stat_semester_third': 'الفصل الثالث',
  'stat_group': 'المجموعة',
  'stat_count': 'العدد',
  'stat_sms_sent': 'تم الإرسال',
  'stat_sms_not_sent': 'لم يرسل',

  // ---------------------------------------------------------------------------
  // Services / Addons
  // ---------------------------------------------------------------------------
  'addons': 'الإضافات',
  'activate': 'تفعيل',
  'subscribe': 'اشتراك',
  'annualSubscription': 'اشتراك سنوي',
  'price': 'السعر',
  'recommended': 'موصى به',
  'goToCart': 'الذهاب إلى السلة',
  'activateNow': 'تفعيل الآن',
  'trial': 'تجربة مجانية',
  'trialDays': 'أيام التجربة',
  'subscriptionActive': 'الاشتراك فعّال',
  'subscriptionExpired': 'الاشتراك منتهي',
  'renewSubscription': 'تجديد الاشتراك',
  'subscriptionExpiresOn': 'ينتهي الاشتراك في',
  'freeTrialEndsOn': 'تنتهي التجربة المجانية في',
  'features': 'المميزات',
  'serviceDetails': 'تفاصيل الخدمة',

  // ---------------------------------------------------------------------------
  // Short Links
  // ---------------------------------------------------------------------------
  'shortLinks': 'الروابط المختصرة',
  'createShortLink': 'إنشاء رابط مختصر',
  'originalUrl': 'الرابط الأصلي',
  'shortUrl': 'الرابط المختصر',
  'clickCount': 'عدد النقرات',
  'linkCopied': 'تم نسخ الرابط',

  // ---------------------------------------------------------------------------
  // Notifications
  // ---------------------------------------------------------------------------
  'notificationCenter': 'مركز الإشعارات',
  'markAsRead': 'تعيين كمقروء',
  'markAllAsRead': 'تعيين الكل كمقروء',
  'noNotifications': 'لا توجد إشعارات',
  'newNotification': 'إشعار جديد',

  // ---------------------------------------------------------------------------
  // Questionnaires
  // ---------------------------------------------------------------------------
  'questionnaires': 'الاستبيانات',
  'createQuestionnaire': 'إنشاء استبيان',
  'questionnaireTitle': 'عنوان الاستبيان',
  'questions': 'الأسئلة',
  'addQuestion': 'إضافة سؤال',
  'responses': 'الردود',
  'responseCount': 'عدد الردود',

  // ---------------------------------------------------------------------------
  // Occasion Cards
  // ---------------------------------------------------------------------------
  'occasionCards': 'بطاقات المناسبات',
  'createCard': 'إنشاء بطاقة',
  'selectOccasion': 'اختر المناسبة',
  'cardTemplate': 'قالب البطاقة',
  'customizeCard': 'تخصيص البطاقة',
  'sendCard': 'إرسال البطاقة',

  // ---------------------------------------------------------------------------
  // Contact Me
  // ---------------------------------------------------------------------------
  'contactMe': 'تواصل معي',
  'contactForm': 'نموذج التواصل',
  'yourMessage': 'رسالتك',
  'sendRequest': 'إرسال الطلب',
  'requestSent': 'تم إرسال طلبك بنجاح',

  // ---------------------------------------------------------------------------
  // Interaction
  // ---------------------------------------------------------------------------
  'interaction': 'التفاعل',
  'interactionReports': 'تقارير التفاعل',
  'interactionRate': 'نسبة التفاعل',

  // ---------------------------------------------------------------------------
  // Files
  // ---------------------------------------------------------------------------
  'files': 'الملفات',
  'uploadFile': 'رفع ملف',
  'fileSize': 'حجم الملف',
  'fileType': 'نوع الملف',
  'fileName': 'اسم الملف',
  'downloadFile': 'تحميل الملف',
  'deleteFile': 'حذف الملف',
  'noFiles': 'لا توجد ملفات',

  // ---------------------------------------------------------------------------
  // Certifications
  // ---------------------------------------------------------------------------
  'certifications': 'الشهادات',
  'createCertification': 'إنشاء شهادة',
  'certificationTemplate': 'قالب الشهادة',
  'recipientName': 'اسم المستلم',
  'issuedDate': 'تاريخ الإصدار',
  'downloadCertification': 'تحميل الشهادة',

  // ---------------------------------------------------------------------------
  // Validation Messages
  // ---------------------------------------------------------------------------
  'requiredField': 'هذا الحقل مطلوب',
  'invalidEmail': 'البريد الإلكتروني غير صالح',
  'invalidPhone': 'رقم الهاتف غير صالح',
  'passwordTooShort': 'كلمة المرور قصيرة جداً (8 أحرف على الأقل)',
  'passwordsDontMatch': 'كلمات المرور غير متطابقة',
  'minLength': 'الحد الأدنى للطول هو {min} أحرف',
  'maxLength': 'الحد الأقصى للطول هو {max} حرف',
  'invalidUsername': 'اسم المستخدم غير صالح',
  'invalidNumber': 'الرجاء إدخال رقم صحيح',
  'passwordRequirements':
      'يجب أن تحتوي كلمة المرور على حرف كبير وحرف صغير ورقم ورمز خاص',

  // ---------------------------------------------------------------------------
  // Error Messages
  // ---------------------------------------------------------------------------
  'networkError': 'خطأ في الشبكة. تحقق من اتصالك بالإنترنت.',
  'serverError': 'خطأ في الخادم. حاول مرة أخرى لاحقاً.',
  'sessionExpired': 'انتهت الجلسة',
  'pleaseLoginAgain': 'الرجاء تسجيل الدخول مرة أخرى',
  'unknownError': 'حدث خطأ غير معروف',
  'tryAgain': 'حاول مرة أخرى',
  'connectionTimeout': 'انتهت مهلة الاتصال',
  'unauthorizedAccess': 'وصول غير مصرح به',
  'forbidden': 'ليس لديك صلاحية للوصول',
  'notFound': 'غير موجود',
  'tooManyRequests': 'طلبات كثيرة جداً. حاول بعد قليل.',
  'maintenanceMode': 'التطبيق تحت الصيانة. حاول لاحقاً.',

  // ---------------------------------------------------------------------------
  // Navigation
  // ---------------------------------------------------------------------------
  'home': 'الرئيسية',
  'messages': 'الرسائل',
  // 'groups' is already defined above
  // 'balance' is already defined above
  // 'more' is already defined above

  // ---------------------------------------------------------------------------
  // Time / Date
  // ---------------------------------------------------------------------------
  'today': 'اليوم',
  'yesterday': 'أمس',
  'daysAgo': 'منذ {count} أيام',
  'hoursAgo': 'منذ {count} ساعات',
  'minutesAgo': 'منذ {count} دقائق',
  'justNow': 'الآن',
  'seconds': 'ثوانٍ',
  'minutes': 'دقائق',
  'hours': 'ساعات',
  'days': 'أيام',

  // ---------------------------------------------------------------------------
  // Absence Messages
  // ---------------------------------------------------------------------------
  'absenceMessages': 'رسائل الغياب والتأخر',
  'absenceMessagesDescription': 'إدارة رسائل الغياب والتأخر المرسلة لأولياء الأمور',
  'sendAbsenceMessage': 'إرسال رسالة غياب',
  'absence': 'غياب',
  'tardiness': 'تأخر',
  'senderNameFilter': 'إسم المرسل',
  'messageTypeFilter': 'نوع الرسالة',
  'messageClassification': 'تصنيف الرسالة',
  'hijriDate': 'التاريخ الهجري',
  'fromDate': 'من تاريخ',
  'toDate': 'إلى تاريخ',
  'selectSender': 'اختر المرسل',
  'selectType': 'اختر النوع',
  'selectClassification': 'اختر التصنيف',
  'allMessages': 'الكل',
  'sentMessages': 'تم الإرسال',
  'failedMessages_': 'فشل',
  'pendingMessages_': 'قيد الإنتظار',
  'sendTime': 'وقت الإرسال',
  'receiveTime': 'وقت الإستلام',
  'recipientCountLabel': 'عدد المستلمين',
  'statusAccepted': 'مقبولة',
  'statusRejected': 'مرفوضة',
  'statusExpired': 'منتهي',
  'statusUnderReview': 'تحت المراجعة',
  'view': 'عرض',
  'report': 'تقرير',
  'searchAbsenceMessages': 'بحث في رسائل الغياب والتأخر...',
  'noAbsenceMessages': 'لا توجد رسائل',

  // ---------------------------------------------------------------------------
  // Statements & Responses
  // ---------------------------------------------------------------------------
  'statements': 'الإفادات والردود',
  'statementsDescription': 'استعرض رسائل ردود المستخدمين على الرسائل المرسلة.',
  'exportResponses': 'تصدير الردود',
  'responseText': 'نص الرد',
  'senderAccount': 'حساب المرسل',
  'responseTime': 'وقت الرد',
  'attachmentLabel': 'مرفق',
  'shortStatements': 'قصيرة',
  'voiceStatements': 'صوتية',
  'longStatements': 'طويلة',
  'unregisteredNumbers': 'أرقام غير مسجلة',
  'absenceAndTardiness': 'غياب وتأخير',
  'generalSearch': 'بحث عام',
  'generalSearchHint': 'بحث بالنص: الرسالة، اسم المرسل',
  'groupFilter': 'مجموعة',
  'noResponses': 'لا توجد ردود',
  'deleteResponse': 'حذف الرد',
  'confirmDeleteResponse': 'هل أنت متأكد من حذف هذا الرد؟',
  'responseDeleted': 'تم حذف الرد بنجاح',
  'exportRequested': 'تم طلب تصدير الردود بنجاح',
  'viewMessageAction': 'عرض الرسالة',
  'originalMessage': 'الرسالة الأصلية',
  'downloadAttachment': 'تحميل المرفق',
  'filterStatements': 'تصفية الإفادات',
  'searchStatements': 'بحث في الإفادات والردود...',

  // Statement Types
  'statement_type_all': 'الكل',
  'statement_type_short': 'قصيرة',
  'statement_type_voice': 'صوتية',
  'statement_type_long': 'طويلة',
  'statement_type_unregistered': 'أرقام غير مسجلة',
  'statement_type_absence': 'غياب',
  'statement_type_tardiness': 'التأخير',
  'statement_type_absence_and_tardiness': 'غياب وتأخير',

  // Statements Screen UI
  'statement_delete_title': 'حذف الرد',
  'statement_confirm_delete': 'هل أنت متأكد من حذف هذا الرد؟',
  'statement_deleted': 'تم حذف الرد بنجاح',
  'statement_export_requested': 'تم طلب تصدير الردود بنجاح',
  'statement_no_responses': 'لا توجد ردود',
  'statement_no_responses_in': 'لا توجد ردود في هذا القسم',
  'statement_view_message': 'عرض الرسالة',
  'statement_response_text': 'نص الرد:',
  'statement_original_message': 'الرسالة الأصلية:',
  'statement_filter_title': 'تصفية الإفادات',
  'statement_search_hint': 'بحث في الإفادات والردود...',
  'statement_general_search': 'بحث عام',
  'statement_search_text_hint': 'بحث بالنص: الرسالة، اسم المرسل',
  'statement_name_label': 'الإسم',
  'statement_enter_name': 'أدخل الإسم',
  'statement_sender_name': 'إسم المرسل',
  'statement_enter_sender_name': 'أدخل إسم المرسل',
  'statement_date_range': 'الفترة الزمنية',
  'statement_from_date': 'من تاريخ',
  'statement_to_date': 'إلى تاريخ',
  'statement_responses_deleted': 'تم حذف الردود بنجاح',
  'statement_responses_delete_failed': 'فشل حذف الردود',
  'statement_download_attachment': 'تحميل المرفق',

  // ---------------------------------------------------------------------------
  // More Screen Sections & Help
  // ---------------------------------------------------------------------------
  'messagesSection': 'الرسائل',
  'messageTools': 'أدوات الرسائل',
  'servicesAndStatistics': 'الخدمات والإحصائيات',
  'account': 'الحساب',
  'helpSection': 'المساعدة',
  'environmentRules': 'ملف ضوابط البيئة للرسائل',
  'userGuide': 'دليل المستخدم',
  'reportProblem': 'الإبلاغ عن مشكلة',
  'helpAndSupport': 'المساعدة والدعم',

  // ---------------------------------------------------------------------------
  // Miscellaneous
  // ---------------------------------------------------------------------------
  'welcomeMessage': 'مرحباً بك في اوربت SMS',
  'onboardingTitle1': 'إرسال رسائل جماعية',
  'onboardingDesc1': 'أرسل رسائلك لآلاف الأرقام بضغطة زر واحدة',
  'onboardingTitle2': 'إدارة جهات الاتصال',
  'onboardingDesc2': 'نظّم جهات اتصالك في مجموعات لسهولة الإرسال',
  'onboardingTitle3': 'تتبع وإحصائيات',
  'onboardingDesc3': 'تابع حالة رسائلك وإحصائيات الإرسال بشكل مفصّل',
  'getStarted': 'ابدأ الآن',
  'poweredBy': 'مدعوم من اوربت',
  'copyright': 'جميع الحقوق محفوظة',

  // ---------------------------------------------------------------------------
  // Shared Widgets
  // ---------------------------------------------------------------------------
  'searchHint': 'بحث...',
  'dateRangeLabel': 'الفترة الزمنية',
  'selectDateRange': 'اختر الفترة',
  'loadingError': 'حدث خطأ أثناء تحميل البيانات',
  'payment': 'الدفع',
  'closePaymentPage': 'إغلاق صفحة الدفع',
  'confirmClosePayment': 'هل أنت متأكد من إغلاق صفحة الدفع؟',
  'continuePayment': 'استمرار',
  'reloadPage': 'إعادة تحميل',
  'paymentFailure': 'فشلت عملية الدفع',
  'paymentUnconfirmed': 'لم يتم تأكيد عملية الدفع، يرجى التحقق من رصيدك',
  'openingFile': 'جاري فتح الملف...',
  'fileDisplayError': 'تعذر عرض الملف',
  'fileLoadError': 'تعذر تحميل الملف',
  'openExternally': 'فتح خارجياً',
  'openWithExternalApp': 'فتح بتطبيق خارجي',
  'termsOfUse': 'سياسة الاستخدام',

  // ---------------------------------------------------------------------------
  // Bottom Navigation
  // ---------------------------------------------------------------------------
  'navHome': 'الرئيسية',
  'navMessages': 'الرسائل',
  'navGroups': 'المجموعات',
  'navBalance': 'الرصيد',
  'navMore': 'المزيد',

  // ---------------------------------------------------------------------------
  // Validators
  // ---------------------------------------------------------------------------
  'fieldNameRequired': '{field} مطلوب',
  'emailRequired': 'البريد الإلكتروني مطلوب',
  'emailInvalid': 'البريد الإلكتروني غير صالح',
  'phoneInvalid': 'رقم الجوال غير صالح',
  'passwordRequired': 'كلمة المرور مطلوبة',
  'passwordTooShortMsg': 'كلمة المرور قصيرة جداً (8 أحرف على الأقل)',
  'passwordNeedsUppercase': 'يجب أن تحتوي على حرف كبير واحد على الأقل',
  'passwordNeedsLowercase': 'يجب أن تحتوي على حرف صغير واحد على الأقل',
  'passwordNeedsDigit': 'يجب أن تحتوي على رقم واحد على الأقل',
  'passwordNeedsSpecial': 'يجب أن تحتوي على رمز خاص واحد على الأقل',
  'confirmPasswordRequired': 'تأكيد كلمة المرور مطلوب',
  'passwordMismatch': 'كلمات المرور غير متطابقة',
  'usernameRequired': 'اسم المستخدم مطلوب',
  'usernameInvalid': 'اسم المستخدم غير صالح (3-30 حرف، أرقام، _ أو -)',
  'valueTooShort': '{field} يجب أن لا يقل عن {min} أحرف',
  'valueTooLong': '{field} يجب أن لا يزيد عن {max} حرف',
  'defaultFieldName': 'القيمة',
  'numberRequired': 'الرجاء إدخال رقم',
  'numberInvalid': 'الرجاء إدخال رقم صحيح',

  // ---------------------------------------------------------------------------
  // Formatters
  // ---------------------------------------------------------------------------
  'timeJustNow': 'الآن',
  'timeMinuteAgo': 'منذ {count} دقيقة',
  'timeMinutesAgo': 'منذ {count} دقائق',
  'timeHourAgo': 'منذ {count} ساعة',
  'timeHoursAgo': 'منذ {count} ساعات',
  'timeYesterday': 'أمس',
  'timeDaysAgo': 'منذ {count} أيام',
  'timeWeekAgo': 'منذ {count} أسبوع',
  'timeWeeksAgo': 'منذ {count} أسابيع',
  'timeMonthAgo': 'منذ {count} شهر',
  'timeMonthsAgo': 'منذ {count} أشهر',
  'timeYearAgo': 'منذ {count} سنة',
  'timeYearsAgo': 'منذ {count} سنوات',
  'smsCountSingular': '{segments} رسالة ({chars} حرف، متبقي {remaining})',
  'smsCountPlural': '{segments} رسائل ({chars} حرف، متبقي {remaining})',
  'currencySymbol': 'ر.س',

  // ---------------------------------------------------------------------------
  // Message Type Labels

  // ---------------------------------------------------------------------------
  // Message Type Labels
  // ---------------------------------------------------------------------------
  'msg_type_from_numbers': 'إرسال إلى أرقام',
  'msg_type_from_numbers_short': 'أرقام',
  'msg_type_from_groups': 'إرسال إلى مجموعات',
  'msg_type_from_groups_short': 'مجموعات',
  'msg_type_from_noor': 'رسائل نور',
  'msg_type_from_noor_short': 'نور',
  'msg_type_custom_messages': 'رسائل مخصصة',
  'msg_type_custom_messages_short': 'مخصصة',
  'msg_type_absence_lateness': 'الغياب والتأخر',
  'msg_type_absence_lateness_short': 'غياب',
  'msg_type_teacher_messages': 'رسائل المعلمين',
  'msg_type_teacher_messages_short': 'معلمين',
  'msg_type_long_messages': 'رسائل طويلة',
  'msg_type_long_messages_short': 'طويلة',
  'msg_type_voice_messages': 'رسائل صوتية',
  'msg_type_voice_messages_short': 'صوتية',
  'msg_type_file_messages': 'رسائل ملفات',
  'msg_type_file_messages_short': 'ملفات',
  'msg_type_thanks_certifications': 'شهادات شكر',
  'msg_type_thanks_certifications_short': 'شكر',
  'msg_type_vip_cards': 'بطاقات VIP',
  'msg_type_vip_cards_short': 'VIP',
  'msg_type_bulk_messages': 'رسائل جماعية',
  'msg_type_bulk_messages_short': 'جماعية',
  'msg_type_attendance_records': 'سجل الحضور',
  'msg_type_attendance_records_short': 'حضور',
  'msg_type_certifications': 'الشهادات',
  'msg_type_certifications_short': 'شهادات',

  // ---------------------------------------------------------------------------
  // Message Status Labels
  // ---------------------------------------------------------------------------
  'msg_status_sent': 'مُرسل',
  'msg_status_delivered': 'تم التوصيل',
  'msg_status_pending': 'قيد الانتظار',
  'msg_status_failed': 'فشل',
  'msg_status_scheduled': 'مجدولة',
  'msg_status_rejected': 'مرفوض',
  'msg_status_expired': 'منتهي',

  // ---------------------------------------------------------------------------
  // Message Card & Message Center
  // ---------------------------------------------------------------------------
  'msg_recipients_count_tooltip': 'عدد المستقبلين',
  'msg_delivered_tooltip': 'تم التوصيل',
  'msg_failed_tooltip': 'فشل',
  'msg_cost_unit': 'رسالة',
  'msg_time_now': 'الآن',
  'msg_time_minutes_ago': 'منذ {count} دقيقة',
  'msg_time_hours_ago': 'منذ {count} ساعة',
  'msg_time_yesterday': 'أمس',
  'msg_time_days_ago': 'منذ {count} أيام',
  'msg_tab_all_messages': 'جميع الرسائل',
  'msg_tab_pending': 'الرسائل المعلقة',
  'msg_tab_attachments': 'المرفقات',
  'msg_tab_templates': 'القوالب',
  'msg_tab_sender_names': 'أسماء المرسلين',
  'msg_tab_short_links': 'اختصار الروابط',
  'msg_new_message': 'رسالة جديدة',
  'msg_advanced_send': 'إرسال متقدم',
  'msg_export_log': 'تصدير السجل',
  'msg_exporting_log': 'جاري تصدير السجل...',
  'msg_search_hint': 'بحث عام (بالنص: الرسالة اسم المرسل)',
  'msg_filter_title': 'تصفية الرسائل',
  'msg_filter_sender_name': 'إسم المرسل',
  'msg_filter_select_sender': 'اختر إسم المرسل',
  'msg_filter_message_type': 'نوع الرسالة',
  'msg_filter_with_attachments': 'مع المرفقات',
  'msg_filter_message_status': 'حالة الرسالة',
  'msg_filter_reset': 'إعادة تعيين الفلاتر',
  'msg_status_chip_all': 'الكل',
  'msg_status_chip_sent': 'تم الإرسال',
  'msg_status_chip_failed': 'فشل',
  'msg_status_chip_pending': 'قيد الإنتظار',
  'msg_load_failed': 'فشل تحميل الرسائل',
  'msg_no_messages': 'لا توجد رسائل',
  'msg_start_first': 'ابدأ بإرسال رسالتك الأولى',

  // ---------------------------------------------------------------------------
  // Messages Pending Tab
  // ---------------------------------------------------------------------------
  'msg_pending_load_failed': 'فشل تحميل الرسائل المعلقة',
  'msg_no_pending': 'لا توجد رسائل معلقة',
  'msg_all_processed': 'جميع الرسائل تمت معالجتها',

  // ---------------------------------------------------------------------------
  // Messages Attachments Tab
  // ---------------------------------------------------------------------------
  'msg_attachments_title': 'المرفقات',
  'msg_attachments_desc': 'استعرض جميع المرفقات المرسلة مع الرسائل',
  'msg_attachments_placeholder': 'سيتم عرض المرفقات هنا عند إرسال رسائل مع ملفات',

  // ---------------------------------------------------------------------------
  // Template Picker
  // ---------------------------------------------------------------------------
  'msg_select_template': 'اختر قالب',
  'msg_new_template': 'جديد',
  'msg_search_template': 'ابحث عن قالب...',
  'msg_templates_load_failed': 'فشل تحميل القوالب',
  'msg_no_matching_results': 'لا توجد نتائج مطابقة',
  'msg_no_saved_templates': 'لا توجد قوالب محفوظة',

  // ---------------------------------------------------------------------------
  // Recipient Input
  // ---------------------------------------------------------------------------
  'msg_recipient_numbers': 'أرقام المستقبلين',
  'msg_number_count': '{count} رقم',
  'msg_number_validation': 'الرقم يجب أن يبدأ بـ 5 ويكون 9 أرقام',
  'msg_number_hint': 'أدخل رقم يبدأ بـ 5 ويتكون من 9 أرقام (مثال: 512345678)',
  'msg_clear_all': 'مسح الكل',

  // ---------------------------------------------------------------------------
  // Message Composer
  // ---------------------------------------------------------------------------
  'msg_message_body_label': 'نص الرسالة',
  'msg_template_btn': 'قالب',
  'msg_variable_btn': 'متغير',
  'msg_insert_variable': 'إدراج متغير',
  'msg_body_hint': 'اكتب نص الرسالة هنا...',
  'msg_char_label': 'حرف',
  'msg_sms_label': 'رسالة',
  'msg_var_student_name': 'اسم الطالب',
  'msg_var_customer_name': 'اسم العميل',
  'msg_var_guardian_name': 'اسم ولي الأمر',
  'msg_var_teacher_name': 'اسم المعلم',
  'msg_var_class_name': 'اسم الفصل',
  'msg_var_school_name': 'اسم المدرسة',
  'msg_var_date': 'التاريخ',
  'msg_var_time': 'الوقت',
  'msg_var_grade': 'الدرجة',
  'msg_var_absence_date': 'تاريخ الغياب',
  'msg_var_company_name': 'اسم الشركة',
  'msg_var_order_number': 'رقم الطلب',

  // ---------------------------------------------------------------------------
  // Schedule Picker
  // ---------------------------------------------------------------------------
  'msg_send_time_label': 'وقت الإرسال',
  'msg_send_now': 'إرسال الآن',
  'msg_send_later': 'إرسال لاحقاً',
  'msg_pick_date': 'اختر التاريخ',
  'msg_pick_time': 'اختر الوقت',
  'msg_date_label': 'التاريخ',
  'msg_time_label': 'الوقت',
  'msg_scheduled_summary': 'سيتم الإرسال في {date} الساعة {time}',

  // ---------------------------------------------------------------------------
  // Send Message Screen
  // ---------------------------------------------------------------------------
  'msg_send_success': 'تم الإرسال بنجاح',
  'msg_send_numbers_count': 'عدد الأرقام: {count}',
  'msg_send_sms_count': 'عدد الرسائل: {count}',
  'msg_send_failed': 'فشل إرسال الرسالة',
  'msg_send_failed_title': 'فشل الإرسال',
  'msg_done': 'تم',
  'msg_ok': 'حسناً',
  'msg_preview_btn': 'معاينة',
  'msg_send_btn': 'إرسال',
  'msg_numbers_tab': 'أرقام',
  'msg_groups_tab': 'مجموعات',
  'msg_groups_label': 'المجموعات',
  'msg_group_count': '{count} مجموعة',
  'msg_number_count_label': '{count} رقم',
  'msg_sender_name_label': 'اسم المرسل',
  'msg_sender_load_failed': 'فشل تحميل أسماء المرسلين',
  'msg_no_senders': 'لا توجد أسماء مرسلين متاحة',
  'msg_select_sender': 'اختر اسم المرسل',
  'msg_groups_load_failed': 'فشل تحميل المجموعات',
  'msg_reload': 'إعادة',
  'msg_no_groups': 'لا توجد مجموعات',
  'msg_total_numbers': '{count} رقم إجمالي',
  'msg_search_name_number': 'بحث بالاسم أو الرقم...',
  'msg_selected_numbers': 'أرقام محددة:',
  'msg_save_count': 'حفظ ({count})',
  'msg_loaded_count': 'تم تحميل {count}',
  'msg_preview_title': 'معاينة الرسالة',
  'msg_preview_recipients': 'عدد المستقبلين',
  'msg_preview_sms_count': 'عدد الرسائل',
  'msg_preview_cost': 'التكلفة المقدرة',
  'msg_preview_cost_value': '{cost} رسالة',
  'msg_preview_body': 'نص الرسالة:',
  'msg_confirm_send': 'تأكيد الإرسال',
  'msg_validate_select_sender': 'الرجاء اختيار اسم المرسل',
  'msg_validate_write_body': 'الرجاء كتابة نص الرسالة',
  'msg_validate_add_recipients': 'الرجاء إضافة أرقام أو اختيار مجموعة',
  'msg_validate_select_datetime': 'الرجاء تحديد تاريخ ووقت الإرسال',

  // ---------------------------------------------------------------------------
  // Auth – Localized strings (added for full i18n coverage)
  // ---------------------------------------------------------------------------

  // Login tab toggle
  'loginTabPhone': 'رقم الجوال',
  'loginTabUsername': 'إسم المستخدم',

  // Country names (phone input)
  'countrySaudiArabia': 'السعودية',
  'countryUAE': 'الإمارات',
  'countryBahrain': 'البحرين',
  'countryKuwait': 'الكويت',
  'countryOman': 'عُمان',
  'countryQatar': 'قطر',
  'countryEgypt': 'مصر',
  'countryJordan': 'الأردن',
  'countryIraq': 'العراق',
  'countryLebanon': 'لبنان',
  'countryYemen': 'اليمن',
  'countrySudan': 'السودان',

  // User type labels
  'userTypeIndividual': 'فرد',
  'userTypeSchool': 'مدرسة',
  'userTypeCompany': 'شركة',
  'userTypeGovernment': 'جهة حكومية',
  'userTypeCharity': 'جمعية خيرية',
  'userTypeUnknown': 'غير محدد',

  // Auth repository fallback messages
  'otpSentSuccess': 'تم إرسال الرمز بنجاح',
  'verificationCodeSent': 'تم إرسال رمز التحقق',
  'passwordResetSuccess': 'تم إعادة تعيين كلمة المرور بنجاح',

  // Login screen
  'welcomeBackTitle': 'مرحباً بعودتك!',
  'signInToAccount': 'سجل دخول إلى حسابك للمتابعة',
  'enterUsername': 'أدخل إسم المستخدم',
  'pleaseEnterUsername': 'الرجاء إدخال إسم المستخدم',
  'enterPassword': 'أدخل كلمة المرور',
  'pleaseEnterPassword': 'الرجاء إدخال كلمة المرور',
  'passwordMinLength6': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
  'loginBySigningIn': 'بتسجيل الدخول فأنت توافق على ',
  'usagePolicy': 'سياسة الاستخدام',

  // Register screen
  'registerNewAccount': 'تسجيل حساب جديد',
  'selectAccountType': 'اختر نوع الحساب',
  'selectAccountTypeDesc': 'حدد نوع حسابك للحصول على الخدمات المناسبة',
  'personalInfo': 'المعلومات الشخصية',
  'enterPersonalInfo': 'أدخل بياناتك الشخصية',
  'enterFullName': 'أدخل الاسم الكامل',
  'nameRequired': 'الاسم مطلوب',
  'emailRequiredMsg': 'البريد الإلكتروني مطلوب',
  'invalidEmailFormat': 'بريد إلكتروني غير صالح',
  'usernameRequiredMsg': 'إسم المستخدم مطلوب',
  'usernameMinLength3': 'الحد الأدنى 3 أحرف',
  'passwordRequiredMsg': 'كلمة المرور مطلوبة',
  'passwordMinLength8': '8 أحرف على الأقل',
  'passwordNeedsSpecialChar': 'يجب أن تحتوي على رمز خاص (!@#\$%^&*)',
  'confirmPasswordHint': 'أعد إدخال كلمة المرور',
  'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
  'genderLabel': 'الجنس',
  'selectGender': 'اختر الجنس',
  'male': 'ذكر',
  'female': 'أنثى',
  'regionLabel': 'المنطقة',
  'selectRegion': 'اختر المنطقة',
  'cityLabel': 'المدينة',
  'selectCity': 'اختر المدينة',
  'selectRegionFirst': 'اختر المنطقة أولاً',
  'documentsTitle': 'المستندات',
  'uploadRequiredDocs': 'ارفع المستندات المطلوبة لإكمال التسجيل',
  'schoolName': 'اسم المدرسة',
  'entityName': 'اسم الجهة',
  'enterNameHint': 'أدخل الاسم',
  'ministerialOrCommercial': 'الرقم الوزاري / السجل التجاري',
  'enterNumber': 'أدخل الرقم',
  'freelanceDocNumber': 'رقم وثيقة العمل الحر',
  'enterDocNumber': 'أدخل رقم الوثيقة',
  'freelanceDoc': 'وثيقة العمل الحر',
  'commercialOrOfficial': 'السجل التجاري / الوثيقة الرسمية',
  'tapToUploadDoc': 'اضغط لرفع المستند',
  'profilePhotoOptional': 'الصورة الشخصية (اختياري)',
  'uploadPhoto': 'رفع صورة',

  // Forgot password screen
  'pleaseEnterPhone': 'الرجاء إدخال رقم الجوال',
  'enterRegisteredPhone': 'أدخل رقم جوالك المسجل لإرسال رمز إعادة التعيين',
  'sendVerificationCode': 'إرسال رمز التحقق',
  'sentSuccessfully': 'تم الإرسال بنجاح',
  'backToLogin': 'الرجوع لتسجيل الدخول',

  // Verify OTP screen
  'verifyPhoneNumber': 'التحقق من رقم الجوال',
  'enterOtpSentToPhone': 'أدخل رمز التحقق المرسل إلى رقم جوالك',
  'codeValidityExpires': 'صلاحية الرمز تنتهي بعد',
  'minuteUnit': 'دقيقة',
  'verifyCode': 'تحقق من الرمز',
  'didNotReceiveCode': 'لم يصلك رمز التحقق؟',
  'resend': 'إعادة الإرسال',

  // Two-factor screen
  'twoStepVerification': 'التحقق بخطوتين',
  'enterCodeSentToDevice': 'أدخل رمز التحقق المرسل إلى جهازك',
  'reLogin': 'إعادة تسجيل الدخول',

  // Reset password screen
  'enterNewPassword': 'أدخل كلمة المرور الجديدة',
  'enterNewPasswordHint': 'أدخل كلمة المرور الجديدة',
  'reEnterPassword': 'أعد إدخال كلمة المرور',
  'passwordStrengthLabel': 'قوة كلمة المرور:',
  'strengthWeak': 'ضعيفة',
  'strengthAcceptable': 'مقبولة',
  'strengthGood': 'جيدة',
  'strengthStrong': 'قوية',
  'doneSuccess': 'تم بنجاح!',
};
