/// Complete Arabic translations for the ORBIT SMS V3 application.
const Map<String, String> ar = {
  // ---------------------------------------------------------------------------
  // Common
  // ---------------------------------------------------------------------------
  'appName': 'اوربت SMS',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  'success': 'تمت العملية بنجاح',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'delete': 'حذف',
  'edit': 'تعديل',
  'save': 'حفظ',
  'search': 'بحث',
  'filter': 'تصفية',
  'export': 'تصدير',
  'import': 'استيراد',
  'refresh': 'تحديث',
  'retry': 'إعادة المحاولة',
  'close': 'إغلاق',
  'back': 'رجوع',
  'next': 'التالي',
  'previous': 'السابق',
  'seeAll': 'عرض الكل',
  'noData': 'لا توجد بيانات',
  'noResults': 'لا توجد نتائج',
  'yes': 'نعم',
  'no': 'لا',
  'ok': 'حسناً',
  'done': 'تم',
  'select': 'اختيار',
  'selectAll': 'تحديد الكل',
  'deselectAll': 'إلغاء تحديد الكل',
  'copy': 'نسخ',
  'copied': 'تم النسخ',
  'share': 'مشاركة',
  'download': 'تحميل',
  'upload': 'رفع',
  'add': 'إضافة',
  'remove': 'إزالة',
  'apply': 'تطبيق',
  'reset': 'إعادة تعيين',
  'submit': 'إرسال',
  'continue_': 'متابعة',
  'skip': 'تخطي',
  'details': 'التفاصيل',
  'more': 'المزيد',
  'less': 'أقل',
  'all': 'الكل',
  'active': 'نشط',
  'inactive': 'غير نشط',
  'enabled': 'مفعّل',
  'disabled': 'معطّل',
  'pending': 'قيد الانتظار',
  'completed': 'مكتمل',
  'failed': 'فشل',
  'sent': 'مُرسل',
  'delivered': 'تم التوصيل',
  'rejected': 'مرفوض',
  'from': 'من',
  'to': 'إلى',
  'date': 'التاريخ',
  'time': 'الوقت',
  'status': 'الحالة',
  'type': 'النوع',
  'count': 'العدد',
  'total': 'الإجمالي',
  'description': 'الوصف',
  'note': 'ملاحظة',
  'notes': 'ملاحظات',

  // ---------------------------------------------------------------------------
  // Auth
  // ---------------------------------------------------------------------------
  'login': 'تسجيل الدخول',
  'register': 'تسجيل حساب جديد',
  'logout': 'تسجيل الخروج',
  'username': 'اسم المستخدم',
  'password': 'كلمة المرور',
  'currentPassword': 'كلمة المرور الحالية',
  'newPassword': 'كلمة المرور الجديدة',
  'confirmPassword': 'تأكيد كلمة المرور',
  'phone': 'رقم الجوال',
  'email': 'البريد الإلكتروني',
  'forgotPassword': 'نسيت كلمة المرور؟',
  'resetPassword': 'إعادة تعيين كلمة المرور',
  'otpVerification': 'التحقق من رمز OTP',
  'verify': 'تحقق',
  'resendCode': 'إعادة إرسال الرمز',
  'codeExpiresIn': 'ينتهي الرمز خلال',
  'rememberMe': 'تذكرني',
  'termsAndConditions': 'الشروط والأحكام',
  'privacyPolicy': 'سياسة الخصوصية',
  'createAccount': 'إنشاء حساب',
  'welcomeBack': 'مرحباً بعودتك',
  'signInToContinue': 'سجّل الدخول للمتابعة',
  'enterOtpSent': 'أدخل رمز التحقق المرسل إلى',
  'agreeToTerms': 'بالتسجيل أنت توافق على',
  'and': 'و',
  'alreadyHaveAccount': 'لديك حساب بالفعل؟',
  'dontHaveAccount': 'ليس لديك حساب؟',
  'fullName': 'الاسم الكامل',
  'companyName': 'اسم الشركة',
  'changePassword': 'تغيير كلمة المرور',
  'passwordChanged': 'تم تغيير كلمة المرور بنجاح',

  // ---------------------------------------------------------------------------
  // Dashboard
  // ---------------------------------------------------------------------------
  'dashboard': 'لوحة التحكم',
  'currentBalance': 'الرصيد الحالي',
  'messagesUnit': 'رسالة',
  'services': 'الخدمات',
  'consumedPoints': 'النقاط المستهلكة',
  'viewAllOperations': 'عرض كل العمليات',
  'newMessage': 'رسالة جديدة',
  'advancedSend': 'إرسال متقدم',
  'groups': 'المجموعات',
  'subAccounts': 'الحسابات الفرعية',
  'addBalance': 'إضافة رصيد',
  'quickActions': 'إجراءات سريعة',
  'recentOperations': 'العمليات الأخيرة',
  'sendingStatistics': 'إحصائيات الإرسال',
  'todaySent': 'مُرسل اليوم',
  'monthSent': 'مُرسل هذا الشهر',
  'totalSent': 'إجمالي المُرسل',

  // ---------------------------------------------------------------------------
  // Messages
  // ---------------------------------------------------------------------------
  'messageCenter': 'مركز الرسائل',
  'sendMessage': 'إرسال رسالة',
  'sendToNumbers': 'إرسال إلى أرقام',
  'sendToGroups': 'إرسال إلى مجموعات',
  'senderName': 'اسم المرسل',
  'messageBody': 'نص الرسالة',
  'sendNow': 'إرسال الآن',
  'schedule': 'جدولة',
  'scheduleMessage': 'جدولة الرسالة',
  'scheduledDate': 'تاريخ الجدولة',
  'scheduledTime': 'وقت الجدولة',
  'preview': 'معاينة',
  'messageCost': 'تكلفة الرسالة',
  'recipientsCount': 'عدد المستقبلين',
  'smsCount': 'عدد الرسائل',
  'template': 'قالب',
  'selectTemplate': 'اختر قالب',
  'saveAsTemplate': 'حفظ كقالب',
  'messageType': 'نوع الرسالة',
  'characters': 'حرف',
  'remainingCharacters': 'الأحرف المتبقية',
  'enterNumbers': 'أدخل الأرقام',
  'numbersHint': 'أدخل الأرقام مفصولة بسطر جديد',
  'selectSenderName': 'اختر اسم المرسل',
  'messagePreview': 'معاينة الرسالة',
  'confirmSend': 'تأكيد الإرسال',
  'messageSent': 'تم إرسال الرسالة بنجاح',
  'messageScheduled': 'تمت جدولة الرسالة بنجاح',
  'duplicateNumbers': 'أرقام مكررة',
  'invalidNumbers': 'أرقام غير صالحة',
  'removeDuplicates': 'إزالة المكرر',
  'removeInvalid': 'إزالة غير الصالح',

  // ---------------------------------------------------------------------------
  // Groups
  // ---------------------------------------------------------------------------
  'createGroup': 'إنشاء مجموعة',
  'editGroup': 'تعديل المجموعة',
  'deleteGroup': 'حذف المجموعة',
  'groupName': 'اسم المجموعة',
  'numbers': 'الأرقام',
  'addNumber': 'إضافة رقم',
  'importExcel': 'استيراد من Excel',
  'phoneNumber': 'رقم الهاتف',
  'name': 'الاسم',
  'identifier': 'المعرّف',
  'contactsCount': 'عدد جهات الاتصال',
  'addContact': 'إضافة جهة اتصال',
  'editContact': 'تعديل جهة اتصال',
  'deleteContact': 'حذف جهة اتصال',
  'importContacts': 'استيراد جهات اتصال',
  'exportContacts': 'تصدير جهات اتصال',
  'groupCreated': 'تم إنشاء المجموعة بنجاح',
  'groupUpdated': 'تم تحديث المجموعة بنجاح',
  'groupDeleted': 'تم حذف المجموعة بنجاح',
  'contactAdded': 'تمت إضافة جهة الاتصال بنجاح',
  'contactUpdated': 'تم تحديث جهة الاتصال بنجاح',
  'contactDeleted': 'تم حذف جهة الاتصال بنجاح',
  'confirmDeleteGroup': 'هل أنت متأكد من حذف هذه المجموعة؟',
  'confirmDeleteContact': 'هل أنت متأكد من حذف جهة الاتصال هذه؟',
  'noGroups': 'لا توجد مجموعات',
  'noContacts': 'لا توجد جهات اتصال',
  'searchContacts': 'بحث في جهات الاتصال',

  // ---------------------------------------------------------------------------
  // Balance
  // ---------------------------------------------------------------------------
  'balance': 'الرصيد',
  'buyBalance': 'شراء رصيد',
  'transferBalance': 'تحويل رصيد',
  'transactionHistory': 'سجل المعاملات',
  'bankTransfer': 'تحويل بنكي',
  'onlinePayment': 'دفع إلكتروني',
  'stcPay': 'STC Pay',
  'sadad': 'سداد',
  'amount': 'المبلغ',
  'pricePerSms': 'سعر الرسالة',
  'vat': 'ضريبة القيمة المضافة',
  'totalAmount': 'المبلغ الإجمالي',
  'paymentMethod': 'طريقة الدفع',
  'paymentSuccess': 'تمت عملية الدفع بنجاح',
  'paymentFailed': 'فشلت عملية الدفع',
  'transferTo': 'تحويل إلى',
  'transferFrom': 'تحويل من',
  'transferAmount': 'مبلغ التحويل',
  'transferSuccess': 'تم التحويل بنجاح',
  'noTransactions': 'لا توجد معاملات',
  'invoiceNumber': 'رقم الفاتورة',
  'balancePackages': 'باقات الرصيد',
  'customAmount': 'مبلغ مخصص',
  'minimumAmount': 'الحد الأدنى للمبلغ',
  'maximumAmount': 'الحد الأقصى للمبلغ',
  'sar': 'ر.س',

  // Balance Tabs
  'balanceLog': 'سجل الرصيد',
  'packages': 'الباقات',
  'bankInfo': 'معلومات البنك',
  'upgradeJourney': 'رحلة الترقية',
  'requestContractProof': 'طلب إثبات تعاقد',
  'balanceTotal': 'الإجمالي',
  'balanceRemaining': 'المتبقي',
  'balanceConsumed': 'المستهلك',
  'balanceTransferred': 'تم تحويله',
  'balanceExpiresIn': 'سينتهي الرصيد خلال',
  'day': 'يوم',
  'hour': 'ساعة',
  'minute': 'دقيقة',
  'second': 'ثانية',
  'availablePackages': 'الباقات المتاحة',
  'choosePackage': 'اختر الباقة المناسبة لاحتياجاتك',
  'noPackages': 'لا توجد باقات متاحة',
  'buy': 'شراء',
  'bankInfoTitle': 'معلومات البنك',
  'bankInfoSubtitle': 'يمكنك التحويل إلى أحد الحسابات التالية',
  'noBankInfo': 'لا توجد معلومات بنكية',
  'accountName': 'اسم الحساب',
  'accountNumber': 'رقم الحساب',
  'transferToSubAccount': 'تحويل رصيد إلى حساب فرعي',
  'transferHistory': 'سجل التحويلات',
  'noTransferHistory': 'لا توجد تحويلات سابقة',
  'currentLevel': 'مستواك الحالي',
  'progressToNextLevel': 'التقدم نحو المستوى التالي',
  'upgradeLevels': 'مستويات الترقية',
  'current': 'حالي',
  'messagesNeeded': 'رسالة إضافية للوصول إلى المستوى',
  'levelBasic': 'أساسي',
  'levelSilver': 'فضي',
  'levelGold': 'ذهبي',
  'levelPlatinum': 'بلاتيني',
  'levelDiamond': 'ماسي',
  'exportData': 'سيتم تصدير البيانات قريباً',
  'searchLog': 'بحث في السجل...',
  'accepted': 'مقبولة',
  'expired': 'منتهي',

  // ---------------------------------------------------------------------------
  // Archive
  // ---------------------------------------------------------------------------
  'archive': 'الأرشيف',
  'archivedMessages': 'الرسائل المؤرشفة',
  'sender': 'المرسل',
  'recipient': 'المستقبل',
  'message': 'الرسالة',
  'filterByDate': 'تصفية حسب التاريخ',
  'filterBySender': 'تصفية حسب المرسل',
  'filterByStatus': 'تصفية حسب الحالة',
  'cancelPending': 'إلغاء المعلّقة',
  'restore': 'استعادة',
  'startDate': 'تاريخ البداية',
  'endDate': 'تاريخ النهاية',
  'noMessages': 'لا توجد رسائل',
  'messageDetails': 'تفاصيل الرسالة',
  'deliveryReport': 'تقرير التسليم',

  // ---------------------------------------------------------------------------
  // Settings
  // ---------------------------------------------------------------------------
  'settings': 'الإعدادات',
  'profile': 'الملف الشخصي',
  'roles': 'الأدوار',
  'permissions': 'الصلاحيات',
  'invoices': 'الفواتير',
  'apiKeys': 'مفاتيح API',
  'senderNames': 'أسماء المرسلين',
  'contracts': 'العقود',
  'balanceReminder': 'تنبيه الرصيد',
  'help': 'المساعدة',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'الإنجليزية',
  'theme': 'المظهر',
  'lightMode': 'الوضع الفاتح',
  'darkMode': 'الوضع الداكن',
  'systemMode': 'وضع النظام',
  'notifications': 'الإشعارات',
  'notificationSettings': 'إعدادات الإشعارات',
  'enableNotifications': 'تفعيل الإشعارات',
  'notificationSound': 'صوت الإشعار',
  'notificationVibration': 'اهتزاز الإشعار',
  'about': 'حول التطبيق',
  'version': 'الإصدار',
  'termsOfService': 'شروط الخدمة',
  'contactUs': 'تواصل معنا',
  'rateApp': 'قيّم التطبيق',
  'shareApp': 'شارك التطبيق',
  'editProfile': 'تعديل الملف الشخصي',
  'profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
  'deleteAccount': 'حذف الحساب',
  'confirmLogout': 'هل أنت متأكد من تسجيل الخروج؟',
  'confirmDeleteAccount': 'هل أنت متأكد من حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
  'minimumBalanceAlert': 'تنبيه عند وصول الرصيد إلى',
  'addSenderName': 'إضافة اسم مرسل',
  'senderNameStatus': 'حالة اسم المرسل',
  'apiKeyGenerated': 'تم إنشاء مفتاح API بنجاح',
  'generateApiKey': 'إنشاء مفتاح API',
  'copyApiKey': 'نسخ مفتاح API',

  // ---------------------------------------------------------------------------
  // Statistics
  // ---------------------------------------------------------------------------
  'statistics': 'الإحصائيات',
  'absenceLateness': 'الغياب والتأخر',
  'customMessages': 'رسائل مخصصة',
  'teacherMessages': 'رسائل المعلمين',
  'exportReport': 'تصدير التقرير',
  'dailyStatistics': 'إحصائيات يومية',
  'weeklyStatistics': 'إحصائيات أسبوعية',
  'monthlyStatistics': 'إحصائيات شهرية',
  'yearlyStatistics': 'إحصائيات سنوية',
  'chart': 'رسم بياني',
  'table': 'جدول',
  'totalMessages': 'إجمالي الرسائل',
  'deliveredMessages': 'الرسائل المُوصلة',
  'failedMessages': 'الرسائل الفاشلة',
  'pendingMessages': 'الرسائل المعلّقة',
  'deliveryRate': 'نسبة التوصيل',

  // ---------------------------------------------------------------------------
  // Services / Addons
  // ---------------------------------------------------------------------------
  'addons': 'الإضافات',
  'activate': 'تفعيل',
  'subscribe': 'اشتراك',
  'annualSubscription': 'اشتراك سنوي',
  'price': 'السعر',
  'recommended': 'موصى به',
  'goToCart': 'الذهاب إلى السلة',
  'activateNow': 'تفعيل الآن',
  'trial': 'تجربة مجانية',
  'trialDays': 'أيام التجربة',
  'subscriptionActive': 'الاشتراك فعّال',
  'subscriptionExpired': 'الاشتراك منتهي',
  'renewSubscription': 'تجديد الاشتراك',
  'subscriptionExpiresOn': 'ينتهي الاشتراك في',
  'freeTrialEndsOn': 'تنتهي التجربة المجانية في',
  'features': 'المميزات',
  'serviceDetails': 'تفاصيل الخدمة',

  // ---------------------------------------------------------------------------
  // Short Links
  // ---------------------------------------------------------------------------
  'shortLinks': 'الروابط المختصرة',
  'createShortLink': 'إنشاء رابط مختصر',
  'originalUrl': 'الرابط الأصلي',
  'shortUrl': 'الرابط المختصر',
  'clickCount': 'عدد النقرات',
  'linkCopied': 'تم نسخ الرابط',

  // ---------------------------------------------------------------------------
  // Notifications
  // ---------------------------------------------------------------------------
  'notificationCenter': 'مركز الإشعارات',
  'markAsRead': 'تعيين كمقروء',
  'markAllAsRead': 'تعيين الكل كمقروء',
  'noNotifications': 'لا توجد إشعارات',
  'newNotification': 'إشعار جديد',

  // ---------------------------------------------------------------------------
  // Questionnaires
  // ---------------------------------------------------------------------------
  'questionnaires': 'الاستبيانات',
  'createQuestionnaire': 'إنشاء استبيان',
  'questionnaireTitle': 'عنوان الاستبيان',
  'questions': 'الأسئلة',
  'addQuestion': 'إضافة سؤال',
  'responses': 'الردود',
  'responseCount': 'عدد الردود',

  // ---------------------------------------------------------------------------
  // Occasion Cards
  // ---------------------------------------------------------------------------
  'occasionCards': 'بطاقات المناسبات',
  'createCard': 'إنشاء بطاقة',
  'selectOccasion': 'اختر المناسبة',
  'cardTemplate': 'قالب البطاقة',
  'customizeCard': 'تخصيص البطاقة',
  'sendCard': 'إرسال البطاقة',

  // ---------------------------------------------------------------------------
  // Contact Me
  // ---------------------------------------------------------------------------
  'contactMe': 'تواصل معي',
  'contactForm': 'نموذج التواصل',
  'yourMessage': 'رسالتك',
  'sendRequest': 'إرسال الطلب',
  'requestSent': 'تم إرسال طلبك بنجاح',

  // ---------------------------------------------------------------------------
  // Interaction
  // ---------------------------------------------------------------------------
  'interaction': 'التفاعل',
  'interactionReports': 'تقارير التفاعل',
  'interactionRate': 'نسبة التفاعل',

  // ---------------------------------------------------------------------------
  // Files
  // ---------------------------------------------------------------------------
  'files': 'الملفات',
  'uploadFile': 'رفع ملف',
  'fileSize': 'حجم الملف',
  'fileType': 'نوع الملف',
  'fileName': 'اسم الملف',
  'downloadFile': 'تحميل الملف',
  'deleteFile': 'حذف الملف',
  'noFiles': 'لا توجد ملفات',

  // ---------------------------------------------------------------------------
  // Certifications
  // ---------------------------------------------------------------------------
  'certifications': 'الشهادات',
  'createCertification': 'إنشاء شهادة',
  'certificationTemplate': 'قالب الشهادة',
  'recipientName': 'اسم المستلم',
  'issuedDate': 'تاريخ الإصدار',
  'downloadCertification': 'تحميل الشهادة',

  // ---------------------------------------------------------------------------
  // Validation Messages
  // ---------------------------------------------------------------------------
  'requiredField': 'هذا الحقل مطلوب',
  'invalidEmail': 'البريد الإلكتروني غير صالح',
  'invalidPhone': 'رقم الهاتف غير صالح',
  'passwordTooShort': 'كلمة المرور قصيرة جداً (8 أحرف على الأقل)',
  'passwordsDontMatch': 'كلمات المرور غير متطابقة',
  'minLength': 'الحد الأدنى للطول هو {min} أحرف',
  'maxLength': 'الحد الأقصى للطول هو {max} حرف',
  'invalidUsername': 'اسم المستخدم غير صالح',
  'invalidNumber': 'الرجاء إدخال رقم صحيح',
  'passwordRequirements':
      'يجب أن تحتوي كلمة المرور على حرف كبير وحرف صغير ورقم ورمز خاص',

  // ---------------------------------------------------------------------------
  // Error Messages
  // ---------------------------------------------------------------------------
  'networkError': 'خطأ في الشبكة. تحقق من اتصالك بالإنترنت.',
  'serverError': 'خطأ في الخادم. حاول مرة أخرى لاحقاً.',
  'sessionExpired': 'انتهت الجلسة',
  'pleaseLoginAgain': 'الرجاء تسجيل الدخول مرة أخرى',
  'unknownError': 'حدث خطأ غير معروف',
  'tryAgain': 'حاول مرة أخرى',
  'connectionTimeout': 'انتهت مهلة الاتصال',
  'unauthorizedAccess': 'وصول غير مصرح به',
  'forbidden': 'ليس لديك صلاحية للوصول',
  'notFound': 'غير موجود',
  'tooManyRequests': 'طلبات كثيرة جداً. حاول بعد قليل.',
  'maintenanceMode': 'التطبيق تحت الصيانة. حاول لاحقاً.',

  // ---------------------------------------------------------------------------
  // Navigation
  // ---------------------------------------------------------------------------
  'home': 'الرئيسية',
  'messages': 'الرسائل',
  // 'groups' is already defined above
  // 'balance' is already defined above
  // 'more' is already defined above

  // ---------------------------------------------------------------------------
  // Time / Date
  // ---------------------------------------------------------------------------
  'today': 'اليوم',
  'yesterday': 'أمس',
  'daysAgo': 'منذ {count} أيام',
  'hoursAgo': 'منذ {count} ساعات',
  'minutesAgo': 'منذ {count} دقائق',
  'justNow': 'الآن',
  'seconds': 'ثوانٍ',
  'minutes': 'دقائق',
  'hours': 'ساعات',
  'days': 'أيام',

  // ---------------------------------------------------------------------------
  // Absence Messages
  // ---------------------------------------------------------------------------
  'absenceMessages': 'رسائل الغياب والتأخر',
  'absenceMessagesDescription': 'إدارة رسائل الغياب والتأخر المرسلة لأولياء الأمور',
  'sendAbsenceMessage': 'إرسال رسالة غياب',
  'absence': 'غياب',
  'tardiness': 'تأخر',
  'senderNameFilter': 'إسم المرسل',
  'messageTypeFilter': 'نوع الرسالة',
  'messageClassification': 'تصنيف الرسالة',
  'hijriDate': 'التاريخ الهجري',
  'fromDate': 'من تاريخ',
  'toDate': 'إلى تاريخ',
  'selectSender': 'اختر المرسل',
  'selectType': 'اختر النوع',
  'selectClassification': 'اختر التصنيف',
  'allMessages': 'الكل',
  'sentMessages': 'تم الإرسال',
  'failedMessages_': 'فشل',
  'pendingMessages_': 'قيد الإنتظار',
  'sendTime': 'وقت الإرسال',
  'receiveTime': 'وقت الإستلام',
  'recipientCountLabel': 'عدد المستلمين',
  'statusAccepted': 'مقبولة',
  'statusRejected': 'مرفوضة',
  'statusExpired': 'منتهي',
  'statusUnderReview': 'تحت المراجعة',
  'view': 'عرض',
  'report': 'تقرير',
  'searchAbsenceMessages': 'بحث في رسائل الغياب والتأخر...',
  'noAbsenceMessages': 'لا توجد رسائل',

  // ---------------------------------------------------------------------------
  // Statements & Responses
  // ---------------------------------------------------------------------------
  'statements': 'الإفادات والردود',
  'statementsDescription': 'استعرض رسائل ردود المستخدمين على الرسائل المرسلة.',
  'exportResponses': 'تصدير الردود',
  'responseText': 'نص الرد',
  'senderAccount': 'حساب المرسل',
  'responseTime': 'وقت الرد',
  'attachmentLabel': 'مرفق',
  'shortStatements': 'قصيرة',
  'voiceStatements': 'صوتية',
  'longStatements': 'طويلة',
  'unregisteredNumbers': 'أرقام غير مسجلة',
  'absenceAndTardiness': 'غياب وتأخير',
  'generalSearch': 'بحث عام',
  'generalSearchHint': 'بحث بالنص: الرسالة، اسم المرسل',
  'groupFilter': 'مجموعة',
  'noResponses': 'لا توجد ردود',
  'deleteResponse': 'حذف الرد',
  'confirmDeleteResponse': 'هل أنت متأكد من حذف هذا الرد؟',
  'responseDeleted': 'تم حذف الرد بنجاح',
  'exportRequested': 'تم طلب تصدير الردود بنجاح',
  'viewMessageAction': 'عرض الرسالة',
  'originalMessage': 'الرسالة الأصلية',
  'downloadAttachment': 'تحميل المرفق',
  'filterStatements': 'تصفية الإفادات',
  'searchStatements': 'بحث في الإفادات والردود...',

  // ---------------------------------------------------------------------------
  // More Screen Sections & Help
  // ---------------------------------------------------------------------------
  'messagesSection': 'الرسائل',
  'messageTools': 'أدوات الرسائل',
  'servicesAndStatistics': 'الخدمات والإحصائيات',
  'account': 'الحساب',
  'helpSection': 'المساعدة',
  'environmentRules': 'ملف ضوابط البيئة للرسائل',
  'userGuide': 'دليل المستخدم',
  'reportProblem': 'الإبلاغ عن مشكلة',
  'helpAndSupport': 'المساعدة والدعم',

  // ---------------------------------------------------------------------------
  // Miscellaneous
  // ---------------------------------------------------------------------------
  'welcomeMessage': 'مرحباً بك في اوربت SMS',
  'onboardingTitle1': 'إرسال رسائل جماعية',
  'onboardingDesc1': 'أرسل رسائلك لآلاف الأرقام بضغطة زر واحدة',
  'onboardingTitle2': 'إدارة جهات الاتصال',
  'onboardingDesc2': 'نظّم جهات اتصالك في مجموعات لسهولة الإرسال',
  'onboardingTitle3': 'تتبع وإحصائيات',
  'onboardingDesc3': 'تابع حالة رسائلك وإحصائيات الإرسال بشكل مفصّل',
  'getStarted': 'ابدأ الآن',
  'poweredBy': 'مدعوم من اوربت',
  'copyright': 'جميع الحقوق محفوظة',
};
