/// Complete English translations for the ORBIT SMS V3 application.
const Map<String, String> en = {
  // ---------------------------------------------------------------------------
  // Common
  // ---------------------------------------------------------------------------
  'appName': 'ORBIT SMS',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Operation completed successfully',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'delete': 'Delete',
  'edit': 'Edit',
  'save': 'Save',
  'search': 'Search',
  'filter': 'Filter',
  'export': 'Export',
  'import': 'Import',
  'refresh': 'Refresh',
  'retry': 'Retry',
  'close': 'Close',
  'back': 'Back',
  'next': 'Next',
  'previous': 'Previous',
  'seeAll': 'See All',
  'noData': 'No data available',
  'noResults': 'No results found',
  'yes': 'Yes',
  'no': 'No',
  'ok': 'OK',
  'done': 'Done',
  'select': 'Select',
  'selectAll': 'Select All',
  'deselectAll': 'Deselect All',
  'copy': 'Copy',
  'copied': 'Copied',
  'share': 'Share',
  'download': 'Download',
  'upload': 'Upload',
  'add': 'Add',
  'remove': 'Remove',
  'apply': 'Apply',
  'reset': 'Reset',
  'submit': 'Submit',
  'continue_': 'Continue',
  'skip': 'Skip',
  'details': 'Details',
  'more': 'More',
  'less': 'Less',
  'all': 'All',
  'active': 'Active',
  'inactive': 'Inactive',
  'enabled': 'Enabled',
  'disabled': 'Disabled',
  'pending': 'Pending',
  'completed': 'Completed',
  'failed': 'Failed',
  'sent': 'Sent',
  'delivered': 'Delivered',
  'rejected': 'Rejected',
  'from': 'From',
  'to': 'To',
  'date': 'Date',
  'time': 'Time',
  'status': 'Status',
  'type': 'Type',
  'count': 'Count',
  'total': 'Total',
  'description': 'Description',
  'note': 'Note',
  'notes': 'Notes',

  // ---------------------------------------------------------------------------
  // Auth
  // ---------------------------------------------------------------------------
  'login': 'Login',
  'register': 'Register',
  'logout': 'Logout',
  'username': 'Username',
  'password': 'Password',
  'currentPassword': 'Current Password',
  'newPassword': 'New Password',
  'confirmPassword': 'Confirm Password',
  'phone': 'Phone Number',
  'email': 'Email',
  'forgotPassword': 'Forgot Password?',
  'resetPassword': 'Reset Password',
  'otpVerification': 'OTP Verification',
  'verify': 'Verify',
  'resendCode': 'Resend Code',
  'codeExpiresIn': 'Code expires in',
  'rememberMe': 'Remember Me',
  'termsAndConditions': 'Terms & Conditions',
  'privacyPolicy': 'Privacy Policy',
  'createAccount': 'Create Account',
  'welcomeBack': 'Welcome Back',
  'signInToContinue': 'Sign in to continue',
  'enterOtpSent': 'Enter the verification code sent to',
  'agreeToTerms': 'By registering you agree to',
  'and': 'and',
  'alreadyHaveAccount': 'Already have an account?',
  'dontHaveAccount': "Don't have an account?",
  'fullName': 'Full Name',
  'companyName': 'Company Name',
  'changePassword': 'Change Password',
  'passwordChanged': 'Password changed successfully',

  // ---------------------------------------------------------------------------
  // Dashboard
  // ---------------------------------------------------------------------------
  'dashboard': 'Dashboard',
  'currentBalance': 'Current Balance',
  'messagesUnit': 'messages',
  'services': 'Services',
  'consumedPoints': 'Consumed Points',
  'viewAllOperations': 'View All Operations',
  'newMessage': 'New Message',
  'advancedSend': 'Advanced Send',
  'groups': 'Groups',
  'subAccounts': 'Sub Accounts',
  'addBalance': 'Add Balance',
  'quickActions': 'Quick Actions',
  'recentOperations': 'Recent Operations',
  'sendingStatistics': 'Sending Statistics',
  'todaySent': 'Sent Today',
  'monthSent': 'Sent This Month',
  'totalSent': 'Total Sent',
  'dashboardWelcomeDesc': 'Welcome to ORBIT SMS dashboard, manage your account and send messages easily',
  'accountStats': 'Account Statistics',
  'viewAllServices': 'View All Services',
  'manageGroups': 'Manage Groups',
  'manageAccounts': 'Manage Accounts',
  'groupUnit': 'group',
  'accountUnit': 'account',
  'buyNewBalance': 'Buy New Balance',
  'sendingReports': 'Sending Reports',
  'loadingDataError': 'Error loading data',
  'selectMessageType': 'Select Message Type',
  'normalSms': 'Normal SMS',
  'normalSmsDesc': 'Send short text messages',
  'groupSms': 'Group SMS',
  'groupSmsDesc': 'Send messages to contact groups',
  'longSms': 'Long SMS',
  'longSmsDesc': 'Send long text messages',
  'voiceSms': 'Voice SMS',
  'voiceSmsDesc': 'Send recorded voice messages',
  'fileSms': 'File SMS',
  'fileSmsDesc': 'Send messages with attached files',
  'recentMessages': 'Recent Messages',
  'unknown': 'Unknown',
  'statusSent_': 'Sent',
  'statusDelivered_': 'Delivered',
  'statusRejected_': 'Rejected',
  'statusFailed_': 'Failed',
  'statusPending__': 'Pending',
  'statusScheduled_': 'Scheduled',
  'statusCancelled_': 'Cancelled',
  'statusExpired__': 'Expired',
  'upgradeToLevel': 'To upgrade to "{level}", you need to recharge {amount} SAR',
  'bannerWelcomeTitle': 'Welcome to ORBIT SMS',
  'bannerWelcomeDesc': 'Send your messages easily and quickly',
  'bannerOffersTitle': 'Exclusive Offers',
  'bannerOffersDesc': 'Get discounts up to 30%',
  'tier_diamond': 'Diamond',
  'tier_gold': 'Gold',
  'tier_silver': 'Silver',
  'tier_bronze': 'Bronze',
  'tier_basic': 'Basic',
  'langToggleAr': 'Ar',

  // ---------------------------------------------------------------------------
  // Messages
  // ---------------------------------------------------------------------------
  'messageCenter': 'Message Center',
  'sendMessage': 'Send Message',
  'sendToNumbers': 'Send to Numbers',
  'sendToGroups': 'Send to Groups',
  'senderName': 'Sender Name',
  'messageBody': 'Message Body',
  'sendNow': 'Send Now',
  'schedule': 'Schedule',
  'scheduleMessage': 'Schedule Message',
  'scheduledDate': 'Scheduled Date',
  'scheduledTime': 'Scheduled Time',
  'preview': 'Preview',
  'messageCost': 'Message Cost',
  'recipientsCount': 'Recipients Count',
  'smsCount': 'SMS Count',
  'template': 'Template',
  'selectTemplate': 'Select Template',
  'saveAsTemplate': 'Save as Template',
  'messageType': 'Message Type',
  'characters': 'characters',
  'remainingCharacters': 'Remaining characters',
  'enterNumbers': 'Enter Numbers',
  'numbersHint': 'Enter numbers separated by a new line',
  'selectSenderName': 'Select Sender Name',
  'messagePreview': 'Message Preview',
  'confirmSend': 'Confirm Send',
  'messageSent': 'Message sent successfully',
  'messageScheduled': 'Message scheduled successfully',
  'duplicateNumbers': 'Duplicate numbers',
  'invalidNumbers': 'Invalid numbers',
  'removeDuplicates': 'Remove duplicates',
  'removeInvalid': 'Remove invalid',

  // ---------------------------------------------------------------------------
  // Groups
  // ---------------------------------------------------------------------------
  'createGroup': 'Create Group',
  'editGroup': 'Edit Group',
  'deleteGroup': 'Delete Group',
  'groupName': 'Group Name',
  'numbers': 'Numbers',
  'addNumber': 'Add Number',
  'importExcel': 'Import from Excel',
  'phoneNumber': 'Phone Number',
  'name': 'Name',
  'identifier': 'Identifier',
  'contactsCount': 'Contacts Count',
  'addContact': 'Add Contact',
  'editContact': 'Edit Contact',
  'deleteContact': 'Delete Contact',
  'importContacts': 'Import Contacts',
  'exportContacts': 'Export Contacts',
  'groupCreated': 'Group created successfully',
  'groupUpdated': 'Group updated successfully',
  'groupDeleted': 'Group deleted successfully',
  'contactAdded': 'Contact added successfully',
  'contactUpdated': 'Contact updated successfully',
  'contactDeleted': 'Contact deleted successfully',
  'confirmDeleteGroup': 'Are you sure you want to delete this group?',
  'confirmDeleteContact': 'Are you sure you want to delete this contact?',
  'noGroups': 'No groups found',
  'noContacts': 'No contacts found',
  'searchContacts': 'Search contacts',
  'searchGroups': 'Search groups...',
  'showTrashed': 'Show trashed',
  'numberUnit': 'number',
  'startCreatingGroup': 'Start by creating a new group to organize your numbers',
  'exportingGroups': 'Exporting groups...',
  'exportFailed': 'Export failed',
  'groupNameUpdated': 'Name updated successfully',
  'groupNameUpdateFailed': 'Failed to update name',
  'groupRestored': 'Group restored',
  'confirmDeleteGroupNamed': 'Are you sure you want to delete the group',
  'editGroupName': 'Edit group name',
  'addNumbers': 'Add numbers',
  'addNumberManual': 'Add number manually',
  'addNumberManualSubtitle': 'Enter the name and phone number manually',
  'addFromContacts': 'Add from contacts',
  'addFromContactsSubtitle': 'Import Saudi mobile numbers from your device',
  'numberUpdated': 'Number updated',
  'numberAdded': 'Added successfully',
  'deleteNumber': 'Delete number',
  'confirmDeleteNumber': 'Are you sure you want to delete',
  'numberDeleted': 'Number deleted',
  'noNumbers': 'No numbers found',
  'addNumbersOrImport': 'Add numbers to this group or import them from an Excel file',
  'exporting': 'Exporting...',
  'trashed': 'Trashed',
  'createNewGroup': 'Create new group',
  'enterGroupName': 'Enter group name',
  'groupNameRequired': 'Group name is required',
  'groupNameMinLength': 'Group name must be at least 2 characters',
  'createGroupButton': 'Create Group',
  'addNumbersAfterCreate': 'You can add numbers to the group after creating it',
  'editNumber': 'Edit number',
  'addNewNumber': 'Add new number',
  'contactNameLabel': 'Name',
  'enterContactName': 'Enter contact name',
  'phoneNumberRequired': 'Phone number is required',
  'identifierOptional': 'Identifier (optional)',
  'identifierHint': 'ID number or employee number',
  'importNumbers': 'Import numbers',
  'standardImport': 'Standard import',
  'customImport': 'Custom import',
  'contactsTab': 'Contacts',
  'standardImportInfo': 'Maximum 5000 rows. File must contain columns: name, phone number',
  'customImportInfo': 'Map file columns to the required fields',
  'contactsImportInfo': 'Select contacts from your device to import into the group',
  'phoneColumnRequired': 'Phone column is required',
  'groupColumnRequired': 'Group column is required',
  'contactsPermissionRequired': 'Contacts permission is required',
  'contactsReadError': 'Error reading contacts',
  'importFileError': 'Error creating import file',
  'uploadFileButton': 'Upload file',
  'phoneColumnLabel': 'Phone column *',
  'phoneColumnHint': 'Example: A or phone',
  'nameColumnLabel': 'Name column (optional)',
  'nameColumnHint': 'Example: B or name',
  'identifierColumnLabel': 'Identifier column (optional)',
  'identifierColumnHint': 'Example: C or identifier',
  'groupColumnLabel': 'Group column *',
  'groupColumnHint': 'Example: D or group',
  'selectedContactsCount': '{count} contacts selected',
  'tapToSelectContacts': 'Tap to select contacts',
  'tapToEditSelection': 'Tap to edit selection',
  'importContactsCount': 'Import {count} contacts',
  'tapToSelectExcel': 'Tap to select an Excel file',
  'supportedFormats': 'Supported formats: xlsx, xls, csv',
  'importCompleted': 'Import completed',
  'importSuccessful': 'Successful',
  'importFailed': 'Failed',
  'importAnother': 'Import another',
  'selectContactsTitle': 'Select contacts',
  'confirmCount': 'Confirm ({count})',
  'uploadFailedRetry': 'Upload failed. Please try again.',
  'addFromContactsTitle': 'Add from contacts',
  'saudiNumbersOnlyInfo': 'Only Saudi mobile numbers will be added in all formats (05xx, +966xx, 966xx)',
  'importAllContacts': 'Add all contacts',
  'importAllContactsSubtitle': 'Import all Saudi mobile numbers from your device',
  'selectSpecificContacts': 'Select specific contacts',
  'selectSpecificContactsSubtitle': 'Choose the numbers you want to add',
  'addingContacts': 'Adding contacts...',
  'screenWontSleep': 'Screen will stay on until import completes',
  'additionCompleted': 'Addition completed',
  'addedSuccessfully': 'Added',
  'nonSaudi': 'Non-Saudi',
  'alreadyExists': 'Already exists',
  'contactsAddError': 'Error adding contacts',
  'noSaudiNumbers': 'No Saudi mobile numbers found in contacts',
  'selectNumbers': 'Select numbers',
  'searchByNameOrNumber': 'Search by name or number...',
  'deselectAllFiltered': 'Deselect all',
  'saudiNumberCount': '{count} Saudi numbers',
  'nonSaudiSkipped': '{count} non-Saudi (skipped)',
  'noName': 'No name',
  'addCount': 'Add ({count})',

  // ---------------------------------------------------------------------------
  // Balance
  // ---------------------------------------------------------------------------
  'balance': 'Balance',
  'buyBalance': 'Buy Balance',
  'transferBalance': 'Transfer Balance',
  'transactionHistory': 'Transaction History',
  'bankTransfer': 'Bank Transfer',
  'onlinePayment': 'Online Payment',
  'stcPay': 'STC Pay',
  'sadad': 'SADAD',
  'amount': 'Amount',
  'pricePerSms': 'Price per SMS',
  'vat': 'VAT',
  'totalAmount': 'Total Amount',
  'paymentMethod': 'Payment Method',
  'paymentSuccess': 'Payment completed successfully',
  'paymentFailed': 'Payment failed',
  'transferTo': 'Transfer to',
  'transferFrom': 'Transfer from',
  'transferAmount': 'Transfer amount',
  'transferSuccess': 'Transfer completed successfully',
  'noTransactions': 'No transactions found',
  'invoiceNumber': 'Invoice Number',
  'balancePackages': 'Balance Packages',
  'customAmount': 'Custom Amount',
  'minimumAmount': 'Minimum amount',
  'maximumAmount': 'Maximum amount',
  'sar': 'SAR',

  // Balance Tabs
  'balanceLog': 'Balance Log',
  'packages': 'Packages',
  'bankInfo': 'Bank Info',
  'upgradeJourney': 'Upgrade Journey',
  'requestContractProof': 'Request Contract Proof',
  'balanceTotal': 'Total',
  'balanceRemaining': 'Remaining',
  'balanceConsumed': 'Consumed',
  'balanceTransferred': 'Transferred',
  'balanceExpiresIn': 'Balance expires in',
  'day': 'day',
  'hour': 'hour',
  'minute': 'minute',
  'second': 'second',
  'availablePackages': 'Available Packages',
  'choosePackage': 'Choose the package that suits your needs',
  'noPackages': 'No packages available',
  'buy': 'Buy',
  'bankInfoTitle': 'Bank Information',
  'bankInfoSubtitle': 'You can transfer to one of the following accounts',
  'noBankInfo': 'No bank information available',
  'accountName': 'Account Name',
  'accountNumber': 'Account Number',
  'transferToSubAccount': 'Transfer balance to sub-account',
  'transferHistory': 'Transfer History',
  'noTransferHistory': 'No previous transfers',
  'currentLevel': 'Your Current Level',
  'progressToNextLevel': 'Progress to Next Level',
  'upgradeLevels': 'Upgrade Levels',
  'current': 'Current',
  'messagesNeeded': 'additional messages to reach level',
  'levelBasic': 'Basic',
  'levelSilver': 'Silver',
  'levelGold': 'Gold',
  'levelPlatinum': 'Platinum',
  'levelDiamond': 'Diamond',
  'exportData': 'Data export coming soon',
  'searchLog': 'Search log...',
  'accepted': 'Accepted',
  'expired': 'Expired',

  // Balance Screen - additional keys
  'currentBalanceLabel': 'Your Current Balance',
  'availableMessages': 'available messages',
  'expiryDate': 'Expiry Date',
  'remainingDaysLabel': 'days remaining',
  'transactions': 'Transactions',
  'filterByDateBalance': 'Filter by date',
  'searchTransactions': 'Search transactions...',
  'transactionCount': 'transaction(s)',
  'noTransactionsFound': 'No transactions found',
  'noTransactionsMatchFound': 'No matching transactions found',
  'statusPending': 'Pending',
  'statusApproved': 'Approved',
  'statusWaiting': 'Waiting for review',
  'onlinePaymentNoon': 'Online Payment (Noon)',
  'bankTransferRemittance': 'Bank Remittance',
  'amountSar': 'Amount (SAR)',
  'enterAmountSar': 'Enter amount in Saudi Riyals',
  'amountRequired': 'Amount is required',
  'enterValidAmount': 'Enter a valid amount',
  'baseAmount': 'Base Amount',
  'taxAmount': 'Tax (15%)',
  'smsCountLabel': 'SMS Count',
  'messageUnit': 'message(s)',
  'confirmPurchase': 'Confirm Purchase',
  'priceTable': 'Price Table',
  'quantity': 'Quantity',
  'selectBank': 'Select Bank',
  'depositorName': 'Depositor Name',
  'depositorNameHint': 'Name of the transfer owner',
  'depositorNameRequired': 'Depositor name is required',
  'transferDateLabel': 'Transfer Date',
  'selectDateLabel': 'Select date',
  'transferDateRequired': 'Transfer date is required',
  'receiptOptional': 'Transfer Receipt (optional)',
  'tapToUploadReceipt': 'Tap to upload receipt',
  'phoneStcPay': 'Phone Number (STC Pay)',
  'phoneRequired': 'Phone number is required',
  'nationalId': 'National ID Number',
  'enterNationalId': 'Enter national ID',
  'nationalIdRequired': 'National ID is required',
  'otpSentStcPay': 'Verification code sent to your phone via STC Pay',
  'otpCode': 'Verification Code',
  'enterOtpCode': 'Enter the code sent',
  'confirmOtp': 'Confirm Code',
  'purchaseSuccess': 'Purchase completed successfully',
  'purchaseRequestSent': 'Purchase request sent successfully',
  'selectBankRequired': 'Please select a bank',
  'otpSentInfo': 'Verification code sent',
  'sadadInvoiceCreated': 'SADAD invoice created',
  'invoiceNumberLabel': 'Invoice Number:',
  'validUntil': 'Valid until:',
  'payViaBankOrAtm': 'You can pay via your bank app or ATM',
  'confirmTransfer': 'Confirm Transfer',
  'recipientPhone': 'Recipient Phone Number',
  'enterCount': 'Enter count',
  'countRequired': 'Count is required',
  'enterValidCount': 'Enter a valid count',
  'transferButton': 'Transfer',
  'noPreviousTransfers': 'No previous transfers',
  'bankInfoNotAdded': 'No bank information added yet',
  'copiedLabel': 'Copied',
  'copyTooltip': 'Copy',
  'noPackagesCurrently': 'No SMS packages available currently',
  'popular': 'Popular',
  'additionalAddons': 'additional',
  'smsPrice': 'SMS Price:',
  'transferConfirmMessage': 'Do you want to transfer {amount} messages to {phone}?',
  'needAdditionalMessages': 'You need {count} additional messages to reach {level} level',
  'fromMessages': 'From {count} messages',

  // Notifications - additional keys
  'deleteNotification': 'Delete Notification',
  'confirmDeleteNotification': 'Are you sure you want to delete this notification?',
  'notificationDeleted': 'Notification deleted',
  'exportingData': 'Exporting data',
  'searchNotifications': 'Search notifications...',
  'sendNotificationTitle': 'Send Notification',
  'sendButton': 'Send',
  'noNotificationsFound': 'No notifications found',
  'sendInstantNotifications': 'Send instant notifications to your clients',
  'sendNotificationAction': 'Send Notification',
  'recipientNumbers': 'Recipient Numbers',
  'enterNumbersSeparated': 'Enter numbers separated by commas',
  'enterAtLeastOneNumber': 'Please enter at least one number',
  'notificationText': 'Notification Text',
  'enterNotificationText': 'Enter notification text',
  'notificationTextRequired': 'Please enter notification text',
  'notificationSentSuccess': 'Notification sent successfully',
  'recipientCountPreview': 'Recipient Count',
  'estimatedCost': 'Estimated Cost',
  'notifStatusSent': 'Sent',
  'notifStatusFailed': 'Failed',
  'notifStatusPending': 'Pending',
  'recipientLabel': 'recipient(s)',

  // ---------------------------------------------------------------------------
  // Archive
  // ---------------------------------------------------------------------------
  'archive': 'Archive',
  'archivedMessages': 'Archived Messages',
  'sender': 'Sender',
  'recipient': 'Recipient',
  'message': 'Message',
  'filterByDate': 'Filter by Date',
  'filterBySender': 'Filter by Sender',
  'filterByStatus': 'Filter by Status',
  'cancelPending': 'Cancel Pending',
  'restore': 'Restore',
  'startDate': 'Start Date',
  'endDate': 'End Date',
  'noMessages': 'No messages found',
  'messageDetails': 'Message Details',
  'deliveryReport': 'Delivery Report',

  // Archive Types
  'archive_type_general': 'General Archive',
  'archive_type_custom_messages': 'Custom Messages',
  'archive_type_absence_lateness': 'Absence & Lateness',
  'archive_type_teacher_messages': 'Teacher Messages',
  'archive_type_long_messages': 'Long Messages',
  'archive_type_voice_messages': 'Voice Messages',
  'archive_type_file_messages': 'File Messages',
  'archive_type_thanks_certifications': 'Thanks & Certifications',
  'archive_type_vip_cards': 'VIP Cards',
  'archive_type_bulk_messages': 'Bulk Messages',

  // Archive Send At Filter
  'archive_send_at_all': 'All',
  'archive_send_at_now': 'Now',
  'archive_send_at_later': 'Scheduled',
  'archive_send_at_api': 'Via API',

  // Archive Message Status
  'archive_status_sent': 'Sent',
  'archive_status_delivered': 'Delivered',
  'archive_status_pending': 'Pending',
  'archive_status_failed': 'Failed',
  'archive_status_rejected': 'Rejected',
  'archive_status_scheduled': 'Scheduled',
  'archive_status_cancelled': 'Cancelled',
  'archive_status_expired': 'Expired',
  'archive_status_unknown': 'Unknown',

  // Archive Screen UI
  'archive_filter_title': 'Filter Archive',
  'archive_send_type': 'Send Type',
  'archive_date_range': 'Date Range',
  'archive_phone_number': 'Phone Number',
  'archive_enter_phone': 'Enter phone number',
  'archive_reset_filters': 'Reset',
  'archive_search_hint': 'Search archive...',
  'archive_delete_messages': 'Delete Messages',
  'archive_confirm_delete': 'Are you sure you want to delete {count} messages?',
  'archive_messages_deleted': 'Messages deleted successfully',
  'archive_cancel_messages': 'Cancel Messages',
  'archive_confirm_cancel': 'Are you sure you want to cancel {count} pending messages?',
  'archive_messages_cancelled': 'Messages cancelled successfully',
  'archive_messages_restored': 'Messages restored successfully',
  'archive_export_requested': 'Export requested successfully',
  'archive_no_messages_in': 'No messages in this section',
  'archive_delete_failed': 'Failed to delete messages',
  'archive_cancel_pending_failed': 'Failed to cancel messages',
  'archive_cancel_pending_success': 'Pending messages cancelled successfully',
  'archive_restore_failed': 'Failed to restore messages',

  // ---------------------------------------------------------------------------
  // Settings
  // ---------------------------------------------------------------------------
  'settings': 'Settings',
  'profile': 'Profile',
  'roles': 'Roles',
  'permissions': 'Permissions',
  'invoices': 'Invoices',
  'apiKeys': 'API Keys',
  'senderNames': 'Sender Names',
  'contracts': 'Contracts',
  'balanceReminder': 'Balance Reminder',
  'help': 'Help',
  'language': 'Language',
  'arabic': 'Arabic',
  'english': 'English',
  'theme': 'Theme',
  'lightMode': 'Light Mode',
  'darkMode': 'Dark Mode',
  'systemMode': 'System Mode',
  'notifications': 'Notifications',
  'notificationSettings': 'Notification Settings',
  'enableNotifications': 'Enable Notifications',
  'notificationSound': 'Notification Sound',
  'notificationVibration': 'Notification Vibration',
  'about': 'About',
  'version': 'Version',
  'termsOfService': 'Terms of Service',
  'contactUs': 'Contact Us',
  'rateApp': 'Rate App',
  'shareApp': 'Share App',
  'editProfile': 'Edit Profile',
  'profileUpdated': 'Profile updated successfully',
  'deleteAccount': 'Delete Account',
  'confirmLogout': 'Are you sure you want to logout?',
  'confirmDeleteAccount':
      'Are you sure you want to delete your account? This action cannot be undone.',
  'minimumBalanceAlert': 'Alert when balance reaches',
  'addSenderName': 'Add Sender Name',
  'senderNameStatus': 'Sender Name Status',
  'apiKeyGenerated': 'API key generated successfully',
  'generateApiKey': 'Generate API Key',
  'copyApiKey': 'Copy API Key',

  // ---------------------------------------------------------------------------
  // Settings - Status Labels
  // ---------------------------------------------------------------------------
  'invoice_status_paid': 'Paid',
  'invoice_status_unpaid': 'Unpaid',
  'invoice_status_pending': 'Pending',
  'invoice_status_overdue': 'Overdue',
  'invoice_status_cancelled': 'Cancelled',
  'invoice_status_refunded': 'Refunded',
  'invoice_status_unknown': 'Unknown',
  'contract_status_active': 'Active',
  'contract_status_inactive': 'Inactive',
  'contract_status_pending': 'Under Review',
  'contract_status_expired': 'Expired',
  'contract_status_cancelled': 'Cancelled',
  'contract_status_unknown': 'Unknown',
  'sender_status_pending': 'Under Review',
  'sender_status_approved': 'Approved',
  'sender_status_rejected': 'Rejected',
  'sender_status_active': 'Active',
  'sender_status_inactive': 'Inactive',
  'sender_status_payment_pending': 'Payment Pending',
  'sender_status_unknown': 'Unknown',
  'permission_group_general': 'General',

  // ---------------------------------------------------------------------------
  // Settings - Screens
  // ---------------------------------------------------------------------------
  'settings_section_account': 'Account',
  'settings_profile_subtitle': 'Edit personal information',
  'settings_change_password_subtitle': 'Update your current password',
  'settings_section_management': 'Management',
  'settings_sub_accounts_subtitle': 'Manage sub-users',
  'settings_roles_title': 'Roles & Permissions',
  'settings_roles_subtitle': 'Manage user roles',
  'settings_section_financial': 'Financial',
  'settings_invoices_subtitle': 'View and download invoices',
  'settings_balance_reminder_subtitle': 'Alert settings for low balance',
  'settings_section_technical': 'Technical',
  'settings_api_keys_subtitle': 'Manage API access keys',
  'settings_section_senders': 'Senders',
  'settings_sender_names_subtitle': 'Request and manage sender names',
  'settings_contracts_subtitle': 'Manage contracts and documents',
  'settings_user_default': 'User',
  'settings_balance_reminder_desc': 'You will be notified when your balance drops below the set threshold.',
  'settings_enable_reminder': 'Enable Alert',
  'settings_min_balance': 'Minimum Balance',
  'settings_min_balance_hint': 'e.g. 100',
  'settings_reminder_saved': 'Alert settings saved successfully',
  'settings_reminder_save_error': 'An error occurred while saving',
  'invoices_no_invoices': 'No invoices',
  'invoices_no_match': 'No invoices matching the search',
  'invoices_download_error': 'Cannot download invoice',
  'invoices_invoice_prefix': 'Invoice',
  'invoices_download_pdf': 'Download PDF',
  'invoices_invoice_number': 'Invoice Number',
  'invoices_invoice_date': 'Date',
  'invoices_invoice_status': 'Status',
  'invoices_invoice_amount': 'Amount',
  'invoices_invoice_tax': 'Tax',
  'invoices_invoice_total': 'Total',
  'invoices_payment_method': 'Payment Method',
  'invoices_notes': 'Notes',
  'invoices_items': 'Items',
  'password_strength_weak': 'Weak',
  'password_strength_medium': 'Medium',
  'password_strength_good': 'Good',
  'password_strength_strong': 'Strong',
  'password_choose_strong': 'Make sure to choose a strong password',
  'password_current_label': 'Current Password',
  'password_current_hint': 'Enter current password',
  'password_new_label': 'New Password',
  'password_new_hint': 'Enter new password',
  'password_confirm_label': 'Confirm Password',
  'password_confirm_hint': 'Re-enter new password',
  'password_req_min_chars': 'At least 8 characters',
  'password_req_uppercase': 'One uppercase letter',
  'password_req_lowercase': 'One lowercase letter',
  'password_req_digit': 'At least one digit',
  'password_req_special': 'One special character',
  'password_changed_success': 'Password changed successfully',
  'profile_name_label': 'Name',
  'profile_name_hint': 'Enter your full name',
  'profile_email_label': 'Email',
  'profile_phone_label': 'Phone Number',
  'profile_landphone_label': 'Landline Number',
  'profile_optional': 'Optional',
  'profile_gender': 'Gender',
  'profile_gender_select': 'Select gender',
  'profile_gender_male': 'Male',
  'profile_gender_female': 'Female',
  'profile_org_name': 'Organization Name',
  'profile_save_changes': 'Save Changes',
  'profile_camera': 'Camera',
  'profile_gallery': 'Gallery',
  'profile_delete_photo': 'Delete Photo',
  'profile_photo_updated': 'Photo updated successfully',
  'profile_photo_update_failed': 'Failed to update photo',
  'profile_photo_deleted': 'Photo deleted successfully',
  'profile_photo_delete_failed': 'Failed to delete photo',
  'profile_updated': 'Profile updated successfully',
  'profile_update_failed': 'Failed to update profile',
  'sub_accounts_search': 'Search sub-accounts...',
  'sub_accounts_empty': 'No sub-accounts',
  'sub_accounts_empty_desc': 'Press + to create a new sub-account',
  'sub_accounts_delete_title': 'Delete Sub-Account',
  'sub_accounts_delete_confirm': 'Are you sure you want to delete this sub-account?',
  'sub_accounts_deleted': 'Sub-account deleted',
  'sub_accounts_edit_title': 'Edit Sub-Account',
  'sub_accounts_create_title': 'Create Sub-Account',
  'sub_accounts_otp_sent': 'Verification code sent to phone',
  'sub_accounts_otp_label': 'Verification Code',
  'sub_accounts_otp_hint': 'Enter verification code',
  'sub_accounts_name_label': 'Name',
  'sub_accounts_name_hint': 'Enter name',
  'sub_accounts_password_label': 'Password',
  'sub_accounts_password_hint': 'Enter password',
  'sub_accounts_api_access': 'API Access',
  'sub_accounts_api_access_desc': 'Allow access via API',
  'sub_accounts_updated': 'Sub-account updated',
  'sub_accounts_update_failed': 'Update failed',
  'sub_accounts_create_failed': 'Creation failed',
  'sub_accounts_created': 'Account created successfully',
  'sub_accounts_otp_invalid': 'Invalid verification code',
  'sub_accounts_create_btn': 'Create',
  'roles_empty': 'No roles',
  'roles_empty_desc': 'Press + to create a new role',
  'roles_delete_title': 'Delete Role',
  'roles_delete_confirm': 'Are you sure you want to delete this role?',
  'roles_deleted': 'Role deleted successfully',
  'roles_permission_count': 'permissions',
  'roles_edit_title': 'Edit Role',
  'roles_create_title': 'Create New Role',
  'roles_name_label': 'Role Name',
  'roles_name_hint': 'e.g. Manager',
  'roles_description_label': 'Description',
  'roles_description_hint': 'Optional role description',
  'roles_permissions_label': 'Permissions',
  'roles_create_button': 'Create Role',
  'roles_deselect_all': 'Deselect All',
  'roles_select_all': 'Select All',
  'roles_updated': 'Role updated',
  'roles_created': 'Role created',
  'sender_empty': 'No requests',
  'sender_empty_desc': 'Press + to submit a new sender name request',
  'sender_delete_title': 'Delete Request',
  'sender_delete_confirm': 'Are you sure you want to delete this sender name request?',
  'sender_deleted': 'Request deleted',
  'sender_doc_uploaded': 'Document uploaded successfully',
  'sender_payment_ready': 'Payment link ready',
  'sender_upload_doc': 'Upload Document',
  'sender_payment': 'Payment',
  'sender_create_title': 'New Sender Name Request',
  'sender_review_notice': 'Your request will be reviewed within 1-3 business days. Please attach the required documents.',
  'sender_name_label': 'Sender Name',
  'sender_name_hint': 'e.g. MyCompany',
  'sender_org_label': 'Organization Name',
  'sender_org_hint': 'Official organization name',
  'sender_commercial_register': 'Commercial Register',
  'sender_authorization_letter': 'Authorization Letter',
  'sender_submit': 'Submit Request',
  'sender_upload_file': 'Tap to upload file',
  'sender_submitted': 'Request submitted successfully',
  'sender_submit_failed': 'Failed to submit request',
  'contracts_empty': 'No contracts',
  'contracts_empty_desc': 'Press + to create a new contract',
  'contracts_doc_uploaded': 'Document uploaded successfully',
  'contracts_delete_title': 'Delete Contract',
  'contracts_delete_confirm': 'Are you sure you want to delete this contract?',
  'contracts_deleted': 'Contract deleted',
  'contracts_upload_doc': 'Upload Document',
  'contracts_contract_prefix': 'Contract',
  'contracts_create_title': 'Create New Contract',
  'contracts_org_label': 'Organization Name',
  'contracts_org_hint': 'Official organization name',
  'contracts_notes_label': 'Notes',
  'contracts_notes_hint': 'Additional notes (optional)',
  'contracts_document_label': 'Document',
  'contracts_upload_doc_btn': 'Tap to upload document',
  'contracts_create_button': 'Create Contract',
  'contracts_created': 'Contract created successfully',
  'contracts_create_failed': 'Failed to create contract',
  'api_keys_empty': 'No API keys',
  'api_keys_empty_desc': 'Press + to create a new key',
  'api_keys_create_title': 'Create API Key',
  'api_keys_name_label': 'Key Name',
  'api_keys_name_hint': 'e.g. Mobile App',
  'api_keys_created': 'Key Created',
  'api_keys_save_warning': 'Save this key now. It will not be shown again.',
  'api_keys_copied': 'Key copied',
  'api_keys_understood': 'Got it',
  'api_keys_no_name': 'Unnamed key',
  'api_keys_created_at': 'Created at',
  'api_keys_delete_title': 'Delete Key',
  'api_keys_delete_confirm_prefix': 'Are you sure you want to delete the key',
  'api_keys_delete_confirm_suffix': 'You will not be able to use it after deletion.',
  'api_keys_deleted': 'Key deleted',
  'error_prefix': 'Error',
  'unknown_error': 'An error occurred',
  'operation_completed': 'Operation completed',
  'verify_btn': 'Verify',


  // ---------------------------------------------------------------------------
  // Statistics
  // ---------------------------------------------------------------------------
  'statistics': 'Statistics',
  'absenceLateness': 'Absence & Lateness',
  'customMessages': 'Custom Messages',
  'teacherMessages': 'Teacher Messages',
  'exportReport': 'Export Report',
  'dailyStatistics': 'Daily Statistics',
  'weeklyStatistics': 'Weekly Statistics',
  'monthlyStatistics': 'Monthly Statistics',
  'yearlyStatistics': 'Yearly Statistics',
  'chart': 'Chart',
  'table': 'Table',
  'totalMessages': 'Total Messages',
  'deliveredMessages': 'Delivered Messages',
  'failedMessages': 'Failed Messages',
  'pendingMessages': 'Pending Messages',
  'deliveryRate': 'Delivery Rate',

  // Statistics Types
  'stat_type_absence_lateness': 'Absence & Lateness',
  'stat_type_custom_messages': 'Custom Messages',
  'stat_type_teacher_messages': 'Teacher Messages',

  // Statistics Sub-Types
  'stat_sub_all': 'All',
  'stat_sub_lateness': 'Lateness',
  'stat_sub_absence': 'Absence',
  'stat_sub_academic_weakness': 'Academic Weakness',
  'stat_sub_behavioural_offence': 'Behavioural Offence',
  'stat_sub_distinction': 'Distinction',
  'stat_sub_others': 'Others',
  'stat_sub_guidance': 'Guidance',
  'stat_sub_note': 'Note',

  // Statistics Screen UI
  'stat_no_statistics': 'No statistics found',
  'stat_no_data_in': 'No data in this section',
  'stat_total_results': 'Total results: {count}',
  'stat_page_info': 'Page {current}/{last}',
  'stat_select_period': 'Select period',
  'stat_export_requested': 'Export requested successfully',
  'stat_student_number': 'Student Number',
  'stat_teacher': 'Teacher',
  'stat_semester': 'Semester',
  'stat_semester_first': 'First Semester',
  'stat_semester_second': 'Second Semester',
  'stat_semester_third': 'Third Semester',
  'stat_group': 'Group',
  'stat_count': 'Count',
  'stat_sms_sent': 'Sent',
  'stat_sms_not_sent': 'Not sent',

  // ---------------------------------------------------------------------------
  // Services / Addons
  // ---------------------------------------------------------------------------
  'addons': 'Addons',
  'activate': 'Activate',
  'subscribe': 'Subscribe',
  'annualSubscription': 'Annual Subscription',
  'price': 'Price',
  'recommended': 'Recommended',
  'goToCart': 'Go to Cart',
  'activateNow': 'Activate Now',
  'trial': 'Free Trial',
  'trialDays': 'Trial Days',
  'subscriptionActive': 'Subscription Active',
  'subscriptionExpired': 'Subscription Expired',
  'renewSubscription': 'Renew Subscription',
  'subscriptionExpiresOn': 'Subscription expires on',
  'freeTrialEndsOn': 'Free trial ends on',
  'features': 'Features',
  'serviceDetails': 'Service Details',

  // ---------------------------------------------------------------------------
  // Short Links
  // ---------------------------------------------------------------------------
  'shortLinks': 'Short Links',
  'createShortLink': 'Create Short Link',
  'originalUrl': 'Original URL',
  'shortUrl': 'Short URL',
  'clickCount': 'Click Count',
  'linkCopied': 'Link copied',

  // ---------------------------------------------------------------------------
  // Notifications
  // ---------------------------------------------------------------------------
  'notificationCenter': 'Notification Center',
  'markAsRead': 'Mark as Read',
  'markAllAsRead': 'Mark All as Read',
  'noNotifications': 'No notifications',
  'newNotification': 'New Notification',

  // ---------------------------------------------------------------------------
  // Questionnaires
  // ---------------------------------------------------------------------------
  'questionnaires': 'Questionnaires',
  'createQuestionnaire': 'Create Questionnaire',
  'questionnaireTitle': 'Questionnaire Title',
  'questions': 'Questions',
  'addQuestion': 'Add Question',
  'responses': 'Responses',
  'responseCount': 'Response Count',

  // ---------------------------------------------------------------------------
  // Occasion Cards
  // ---------------------------------------------------------------------------
  'occasionCards': 'Occasion Cards',
  'createCard': 'Create Card',
  'selectOccasion': 'Select Occasion',
  'cardTemplate': 'Card Template',
  'customizeCard': 'Customize Card',
  'sendCard': 'Send Card',

  // ---------------------------------------------------------------------------
  // Contact Me
  // ---------------------------------------------------------------------------
  'contactMe': 'Contact Me',
  'contactForm': 'Contact Form',
  'yourMessage': 'Your Message',
  'sendRequest': 'Send Request',
  'requestSent': 'Your request has been sent successfully',

  // ---------------------------------------------------------------------------
  // Interaction
  // ---------------------------------------------------------------------------
  'interaction': 'Interaction',
  'interactionReports': 'Interaction Reports',
  'interactionRate': 'Interaction Rate',

  // ---------------------------------------------------------------------------
  // Files
  // ---------------------------------------------------------------------------
  'files': 'Files',
  'uploadFile': 'Upload File',
  'fileSize': 'File Size',
  'fileType': 'File Type',
  'fileName': 'File Name',
  'downloadFile': 'Download File',
  'deleteFile': 'Delete File',
  'noFiles': 'No files found',

  // ---------------------------------------------------------------------------
  // Certifications
  // ---------------------------------------------------------------------------
  'certifications': 'Certifications',
  'createCertification': 'Create Certification',
  'certificationTemplate': 'Certification Template',
  'recipientName': 'Recipient Name',
  'issuedDate': 'Issued Date',
  'downloadCertification': 'Download Certification',

  // ---------------------------------------------------------------------------
  // Validation Messages
  // ---------------------------------------------------------------------------
  'requiredField': 'This field is required',
  'invalidEmail': 'Invalid email address',
  'invalidPhone': 'Invalid phone number',
  'passwordTooShort': 'Password is too short (minimum 8 characters)',
  'passwordsDontMatch': 'Passwords do not match',
  'minLength': 'Minimum length is {min} characters',
  'maxLength': 'Maximum length is {max} characters',
  'invalidUsername': 'Invalid username',
  'invalidNumber': 'Please enter a valid number',
  'passwordRequirements':
      'Password must contain an uppercase letter, a lowercase letter, a number, and a special character',

  // ---------------------------------------------------------------------------
  // Error Messages
  // ---------------------------------------------------------------------------
  'networkError': 'Network error. Please check your internet connection.',
  'serverError': 'Server error. Please try again later.',
  'sessionExpired': 'Session Expired',
  'pleaseLoginAgain': 'Please login again',
  'unknownError': 'An unknown error occurred',
  'tryAgain': 'Try Again',
  'connectionTimeout': 'Connection timed out',
  'unauthorizedAccess': 'Unauthorized access',
  'forbidden': 'You do not have permission to access this',
  'notFound': 'Not found',
  'tooManyRequests': 'Too many requests. Please try again later.',
  'maintenanceMode': 'App is under maintenance. Please try again later.',

  // ---------------------------------------------------------------------------
  // Navigation
  // ---------------------------------------------------------------------------
  'home': 'Home',
  'messages': 'Messages',
  // 'groups' is already defined above
  // 'balance' is already defined above
  // 'more' is already defined above

  // ---------------------------------------------------------------------------
  // Time / Date
  // ---------------------------------------------------------------------------
  'today': 'Today',
  'yesterday': 'Yesterday',
  'daysAgo': '{count} days ago',
  'hoursAgo': '{count} hours ago',
  'minutesAgo': '{count} minutes ago',
  'justNow': 'Just now',
  'seconds': 'seconds',
  'minutes': 'minutes',
  'hours': 'hours',
  'days': 'days',

  // ---------------------------------------------------------------------------
  // Absence Messages
  // ---------------------------------------------------------------------------
  'absenceMessages': 'Absence & Tardiness Messages',
  'absenceMessagesDescription': 'Manage absence and tardiness messages sent to parents/guardians',
  'sendAbsenceMessage': 'Send Absence Message',
  'absence': 'Absence',
  'tardiness': 'Tardiness',
  'senderNameFilter': 'Sender Name',
  'messageTypeFilter': 'Message Type',
  'messageClassification': 'Message Classification',
  'hijriDate': 'Hijri Date',
  'fromDate': 'From Date',
  'toDate': 'To Date',
  'selectSender': 'Select Sender',
  'selectType': 'Select Type',
  'selectClassification': 'Select Classification',
  'allMessages': 'All',
  'sentMessages': 'Sent',
  'failedMessages_': 'Failed',
  'pendingMessages_': 'Pending',
  'sendTime': 'Send Time',
  'receiveTime': 'Receive Time',
  'recipientCountLabel': 'Recipients Count',
  'statusAccepted': 'Accepted',
  'statusRejected': 'Rejected',
  'statusExpired': 'Expired',
  'statusUnderReview': 'Under Review',
  'view': 'View',
  'report': 'Report',
  'searchAbsenceMessages': 'Search absence & tardiness messages...',
  'noAbsenceMessages': 'No messages found',

  // ---------------------------------------------------------------------------
  // Statements & Responses
  // ---------------------------------------------------------------------------
  'statements': 'Statements & Responses',
  'statementsDescription': 'View user responses to sent messages.',
  'exportResponses': 'Export Responses',
  'responseText': 'Response Text',
  'senderAccount': 'Sender Account',
  'responseTime': 'Response Time',
  'attachmentLabel': 'Attachment',
  'shortStatements': 'Short',
  'voiceStatements': 'Voice',
  'longStatements': 'Long',
  'unregisteredNumbers': 'Unregistered Numbers',
  'absenceAndTardiness': 'Absence & Tardiness',
  'generalSearch': 'General Search',
  'generalSearchHint': 'Search by text: message, sender name',
  'groupFilter': 'Group',
  'noResponses': 'No responses found',
  'deleteResponse': 'Delete Response',
  'confirmDeleteResponse': 'Are you sure you want to delete this response?',
  'responseDeleted': 'Response deleted successfully',
  'exportRequested': 'Export request submitted successfully',
  'viewMessageAction': 'View Message',
  'originalMessage': 'Original Message',
  'downloadAttachment': 'Download Attachment',
  'filterStatements': 'Filter Statements',
  'searchStatements': 'Search statements & responses...',

  // Statement Types
  'statement_type_all': 'All',
  'statement_type_short': 'Short',
  'statement_type_voice': 'Voice',
  'statement_type_long': 'Long',
  'statement_type_unregistered': 'Unregistered Numbers',
  'statement_type_absence': 'Absence',
  'statement_type_tardiness': 'Tardiness',
  'statement_type_absence_and_tardiness': 'Absence & Tardiness',

  // Statements Screen UI
  'statement_delete_title': 'Delete Response',
  'statement_confirm_delete': 'Are you sure you want to delete this response?',
  'statement_deleted': 'Response deleted successfully',
  'statement_export_requested': 'Export request submitted successfully',
  'statement_no_responses': 'No responses found',
  'statement_no_responses_in': 'No responses in this section',
  'statement_view_message': 'View Message',
  'statement_response_text': 'Response Text:',
  'statement_original_message': 'Original Message:',
  'statement_filter_title': 'Filter Statements',
  'statement_search_hint': 'Search statements & responses...',
  'statement_general_search': 'General Search',
  'statement_search_text_hint': 'Search by text: message, sender name',
  'statement_name_label': 'Name',
  'statement_enter_name': 'Enter name',
  'statement_sender_name': 'Sender Name',
  'statement_enter_sender_name': 'Enter sender name',
  'statement_date_range': 'Date Range',
  'statement_from_date': 'From Date',
  'statement_to_date': 'To Date',
  'statement_responses_deleted': 'Responses deleted successfully',
  'statement_responses_delete_failed': 'Failed to delete responses',
  'statement_download_attachment': 'Download Attachment',

  // ---------------------------------------------------------------------------
  // More Screen Sections & Help
  // ---------------------------------------------------------------------------
  'messagesSection': 'Messages',
  'messageTools': 'Message Tools',
  'servicesAndStatistics': 'Services & Statistics',
  'account': 'Account',
  'helpSection': 'Help',
  'environmentRules': 'Message Environment Rules',
  'userGuide': 'User Guide',
  'reportProblem': 'Report a Problem',
  'helpAndSupport': 'Help & Support',

  // ---------------------------------------------------------------------------
  // Miscellaneous
  // ---------------------------------------------------------------------------
  'welcomeMessage': 'Welcome to ORBIT SMS',
  'onboardingTitle1': 'Send Bulk Messages',
  'onboardingDesc1':
      'Send your messages to thousands of numbers with a single tap',
  'onboardingTitle2': 'Manage Contacts',
  'onboardingDesc2':
      'Organize your contacts into groups for easy messaging',
  'onboardingTitle3': 'Track & Statistics',
  'onboardingDesc3':
      'Follow your message status and sending statistics in detail',
  'getStarted': 'Get Started',
  'poweredBy': 'Powered by ORBIT',
  'copyright': 'All rights reserved',

  // ---------------------------------------------------------------------------
  // Shared Widgets
  // ---------------------------------------------------------------------------
  'searchHint': 'Search...',
  'dateRangeLabel': 'Date Range',
  'selectDateRange': 'Select date range',
  'loadingError': 'An error occurred while loading data',
  'payment': 'Payment',
  'closePaymentPage': 'Close Payment Page',
  'confirmClosePayment': 'Are you sure you want to close the payment page?',
  'continuePayment': 'Continue',
  'reloadPage': 'Reload',
  'paymentFailure': 'Payment failed',
  'paymentUnconfirmed': 'Payment could not be confirmed. Please check your balance.',
  'openingFile': 'Opening file...',
  'fileDisplayError': 'Could not display file',
  'fileLoadError': 'Could not load file',
  'openExternally': 'Open externally',
  'openWithExternalApp': 'Open with external app',
  'termsOfUse': 'Terms of Use',

  // ---------------------------------------------------------------------------
  // Bottom Navigation
  // ---------------------------------------------------------------------------
  'navHome': 'Home',
  'navMessages': 'Messages',
  'navGroups': 'Groups',
  'navBalance': 'Balance',
  'navMore': 'More',

  // ---------------------------------------------------------------------------
  // Validators
  // ---------------------------------------------------------------------------
  'fieldNameRequired': '{field} is required',
  'emailRequired': 'Email is required',
  'emailInvalid': 'Invalid email address',
  'phoneInvalid': 'Invalid phone number',
  'passwordRequired': 'Password is required',
  'passwordTooShortMsg': 'Password is too short (minimum 8 characters)',
  'passwordNeedsUppercase': 'Must contain at least one uppercase letter',
  'passwordNeedsLowercase': 'Must contain at least one lowercase letter',
  'passwordNeedsDigit': 'Must contain at least one digit',
  'passwordNeedsSpecial': 'Must contain at least one special character',
  'confirmPasswordRequired': 'Password confirmation is required',
  'passwordMismatch': 'Passwords do not match',
  'usernameRequired': 'Username is required',
  'usernameInvalid': 'Invalid username (3-30 chars, numbers, _ or -)',
  'valueTooShort': '{field} must be at least {min} characters',
  'valueTooLong': '{field} must not exceed {max} characters',
  'defaultFieldName': 'Value',
  'numberRequired': 'Please enter a number',
  'numberInvalid': 'Please enter a valid number',

  // ---------------------------------------------------------------------------
  // Formatters
  // ---------------------------------------------------------------------------
  'timeJustNow': 'Just now',
  'timeMinuteAgo': '{count} minute ago',
  'timeMinutesAgo': '{count} minutes ago',
  'timeHourAgo': '{count} hour ago',
  'timeHoursAgo': '{count} hours ago',
  'timeYesterday': 'Yesterday',
  'timeDaysAgo': '{count} days ago',
  'timeWeekAgo': '{count} week ago',
  'timeWeeksAgo': '{count} weeks ago',
  'timeMonthAgo': '{count} month ago',
  'timeMonthsAgo': '{count} months ago',
  'timeYearAgo': '{count} year ago',
  'timeYearsAgo': '{count} years ago',
  'smsCountSingular': '{segments} message ({chars} chars, {remaining} remaining)',
  'smsCountPlural': '{segments} messages ({chars} chars, {remaining} remaining)',
  'currencySymbol': 'SAR',

  // ---------------------------------------------------------------------------
  // Auth – Localized strings (added for full i18n coverage)
  // ---------------------------------------------------------------------------

  // Login tab toggle
  'loginTabPhone': 'Phone Number',
  'loginTabUsername': 'Username',

  // Country names (phone input)
  'countrySaudiArabia': 'Saudi Arabia',
  'countryUAE': 'UAE',
  'countryBahrain': 'Bahrain',
  'countryKuwait': 'Kuwait',
  'countryOman': 'Oman',
  'countryQatar': 'Qatar',
  'countryEgypt': 'Egypt',
  'countryJordan': 'Jordan',
  'countryIraq': 'Iraq',
  'countryLebanon': 'Lebanon',
  'countryYemen': 'Yemen',
  'countrySudan': 'Sudan',

  // User type labels
  'userTypeIndividual': 'Individual',
  'userTypeSchool': 'School',
  'userTypeCompany': 'Company',
  'userTypeGovernment': 'Government',
  'userTypeCharity': 'Charity',
  'userTypeUnknown': 'Unknown',

  // Auth repository fallback messages
  'otpSentSuccess': 'Code sent successfully',
  'verificationCodeSent': 'Verification code sent',
  'passwordResetSuccess': 'Password reset successfully',
  'unexpectedError': 'An unexpected error occurred. Please try again.',

  // Login screen
  'welcomeBackTitle': 'Welcome Back!',
  'signInToAccount': 'Sign in to your account to continue',
  'enterUsername': 'Enter username',
  'pleaseEnterUsername': 'Please enter your username',
  'enterPassword': 'Enter password',
  'pleaseEnterPassword': 'Please enter your password',
  'passwordMinLength6': 'Password must be at least 6 characters',
  'loginBySigningIn': 'By signing in you agree to ',
  'usagePolicy': 'Usage Policy',

  // Register screen
  'registerNewAccount': 'Create New Account',
  'selectAccountType': 'Select Account Type',
  'selectAccountTypeDesc': 'Choose your account type to get the right services',
  'personalInfo': 'Personal Information',
  'enterPersonalInfo': 'Enter your personal details',
  'enterFullName': 'Enter full name',
  'nameRequired': 'Name is required',
  'emailRequiredMsg': 'Email is required',
  'invalidEmailFormat': 'Invalid email address',
  'usernameRequiredMsg': 'Username is required',
  'usernameMinLength3': 'Minimum 3 characters',
  'passwordRequiredMsg': 'Password is required',
  'passwordMinLength8': 'At least 8 characters',
  'passwordNeedsSpecialChar': 'Must contain a special character (!@#\$%^&*)',
  'confirmPasswordHint': 'Re-enter password',
  'passwordsDoNotMatch': 'Passwords do not match',
  'genderLabel': 'Gender',
  'selectGender': 'Select gender',
  'male': 'Male',
  'female': 'Female',
  'regionLabel': 'Region',
  'selectRegion': 'Select region',
  'cityLabel': 'City',
  'selectCity': 'Select city',
  'selectRegionFirst': 'Select region first',
  'documentsTitle': 'Documents',
  'uploadRequiredDocs': 'Upload the required documents to complete registration',
  'schoolName': 'School Name',
  'entityName': 'Entity Name',
  'enterNameHint': 'Enter name',
  'ministerialOrCommercial': 'Ministerial Number / Commercial Register',
  'enterNumber': 'Enter number',
  'freelanceDocNumber': 'Freelance Document Number',
  'enterDocNumber': 'Enter document number',
  'freelanceDoc': 'Freelance Document',
  'commercialOrOfficial': 'Commercial Register / Official Document',
  'tapToUploadDoc': 'Tap to upload document',
  'profilePhotoOptional': 'Profile Photo (optional)',
  'uploadPhoto': 'Upload photo',

  // Forgot password screen
  'pleaseEnterPhone': 'Please enter your phone number',
  'enterRegisteredPhone': 'Enter your registered phone number to receive a reset code',
  'sendVerificationCode': 'Send Verification Code',
  'sentSuccessfully': 'Sent Successfully',
  'backToLogin': 'Back to Login',

  // Verify OTP screen
  'verifyPhoneNumber': 'Verify Phone Number',
  'enterOtpSentToPhone': 'Enter the verification code sent to your phone',
  'codeValidityExpires': 'Code expires in',
  'minuteUnit': 'minute',
  'verifyCode': 'Verify Code',
  'didNotReceiveCode': 'Didn\'t receive the code?',
  'resend': 'Resend',

  // Two-factor screen
  'twoStepVerification': 'Two-Step Verification',
  'enterCodeSentToDevice': 'Enter the verification code sent to your device',
  'reLogin': 'Re-login',

  // Reset password screen
  'enterNewPassword': 'Enter new password',
  'enterNewPasswordHint': 'Enter your new password',
  'reEnterPassword': 'Re-enter password',
  'passwordStrengthLabel': 'Password strength:',
  'strengthWeak': 'Weak',
  'strengthAcceptable': 'Acceptable',
  'strengthGood': 'Good',
  'strengthStrong': 'Strong',
  'doneSuccess': 'Done!',

  // ---------------------------------------------------------------------------
  // Addons (Minor Features)
  // ---------------------------------------------------------------------------
  'addonActivated': 'Active',
  'addonFree': 'Free',
  'addonComingSoon': 'Coming Soon',
  'addonStartsFrom': 'Starts from ',
  'addonTrialActivated': 'Trial period activated successfully',
  'addonRedirectingPayment': 'Redirecting to payment page',
  'addonSubscribed': 'Subscribed successfully',
  'addonSubscriptionPlans': 'Subscription Plans',
  'addonActivateTrial': 'Activate Trial Period',
  'addonSubscribeNow': 'Subscribe Now',
  'addonTrialDays': 'trial days',
  'servicesTitle': 'Services',
  'searchServices': 'Search services...',
  'activeFilter': 'Active',
  'noActiveServices': 'No active services',
  'noServices': 'No services found',
  'exploreServices': 'Explore available services to expand your account capabilities',

  // ---------------------------------------------------------------------------
  // Short Links (Minor Features)
  // ---------------------------------------------------------------------------
  'linkCopiedSuccess': 'Link copied',
  'shortLinkCreated': 'Short link created',
  'deleteLink': 'Delete Link',
  'confirmDeleteLink': 'Are you sure you want to delete this short link?',
  'linkDeleted': 'Link deleted',
  'searchLinks': 'Search links...',
  'noLinks': 'No links found',
  'createNewLink': 'Create a new short link',
  'createLink': 'Create Link',
  'enterUrl': 'Please enter the URL',
  'enterValidUrl': 'Please enter a valid URL',
  'create': 'Create',

  // ---------------------------------------------------------------------------
  // Templates (Minor Features)
  // ---------------------------------------------------------------------------
  'editTemplate': 'Edit Template',
  'createNewTemplate': 'Create New Template',
  'templateName': 'Template Name',
  'enterTemplateName': 'Enter template name',
  'enterTemplateNameValidation': 'Please enter the template name',
  'enterMessageBodyValidation': 'Please enter the message body',
  'enterMessageHint': 'Enter message body',
  'update': 'Update',
  'templatesTitle': 'Templates',
  'createTemplateTooltip': 'Create Template',
  'searchTemplates': 'Search templates...',
  'noTemplates': 'No templates found',
  'createTemplateDesc': 'Create a new template to simplify sending messages',
  'deleteTemplate': 'Delete Template',
  'confirmDeleteTemplate': 'Are you sure you want to delete the template',
  'templateDeleted': 'Template deleted successfully',

  // ---------------------------------------------------------------------------
  // Questionnaires (Minor Features)
  // ---------------------------------------------------------------------------
  'questionnaireSent': 'Sent',
  'questionnaireDraft': 'Draft',
  'questionnaireUnsent': 'Unsent',
  'recipientsLabel': 'Recipients',
  'repliesLabel': 'Replies',
  'deleteQuestionnaire': 'Delete Questionnaire',
  'confirmDeleteQuestionnaire': 'Are you sure you want to delete',
  'deletedSuccessfully': 'Deleted successfully',
  'sentTab': 'Sent',
  'unsentTab': 'Unsent',
  'searchQuestionnaires': 'Search questionnaires...',
  'noSentQuestionnaires': 'No sent questionnaires',
  'noUnsentQuestionnaires': 'No unsent questionnaires',

  // ---------------------------------------------------------------------------
  // Occasion Cards (Minor Features)
  // ---------------------------------------------------------------------------
  'sendCardTitle': 'Send Card:',
  'theMessage': 'Message',
  'enterGreeting': 'Enter greeting text',
  'enterMessageValidation': 'Please enter the message',
  'theNumbers': 'Numbers',
  'enterNumbersValidation': 'Please enter the numbers',
  'cardSent': 'Card sent successfully',
  'templatesTab': 'Templates',
  'archiveTab': 'Archive',
  'noCardTemplates': 'No templates found',
  'noSentCards': 'No sent cards',
  'recipientUnit': 'recipient',

  // ---------------------------------------------------------------------------
  // Certifications (Minor Features)
  // ---------------------------------------------------------------------------
  'enterLoginCredentials': 'Please enter login credentials',
  'noorLoginTitle': 'Login to Noor System',
  'noorConnected': 'Connected to Noor system',
  'selectProfile': 'Select Profile',
  'sendCertifications': 'Send Certifications',
  'sendingCertifications': 'Sending certifications',
  'sendTab': 'Send',
  'noCertifications': 'No certifications found',

  // ---------------------------------------------------------------------------
  // Files (Minor Features)
  // ---------------------------------------------------------------------------
  'deleteFileTitle': 'Delete File',
  'confirmDeleteFile': 'Are you sure you want to delete',
  'fileDeleted': 'File deleted',
  'deleteFiles': 'Delete Files',
  'confirmDeleteFiles': 'Are you sure you want to delete',
  'filesWord': 'files',
  'filesDeleted': 'Files deleted',
  'downloadingFile': 'Downloading file',
  'searchFiles': 'Search files...',
  'selectFileToUpload': 'Select a file to upload',
  'deleteSelected': 'Delete Selected',
  'cancelSelection': 'Cancel Selection',
  'noFilesDesc': 'Upload new files using the upload button',

  // ---------------------------------------------------------------------------
  // Contact Me (Minor Features)
  // ---------------------------------------------------------------------------
  'settingsSaved': 'Settings saved',
  'enableContactMe': 'Enable Contact Me service',
  'pageUrl': 'Page URL',
  'saveSettings': 'Save Settings',
  'addReason': 'Add Reason',
  'reasonTitleLabel': 'Reason title',
  'deleteReasonTitle': 'Delete Reason',
  'confirmDeleteReason': 'Are you sure you want to delete',
  'noReasons': 'No reasons found',
  'settingsTab': 'Settings',
  'reasonsTab': 'Reasons',
  'messagesTab': 'Messages',
  'noContactMessages': 'No messages found',
  'incomingMessagesDesc': 'Incoming messages will appear here',

  // ---------------------------------------------------------------------------
  // Interaction (Minor Features)
  // ---------------------------------------------------------------------------
  'interactionMessageHint': 'Enter interaction message text',
  'noReplies': 'No replies found',
  'recipientRepliesDesc': 'Recipient replies will appear here',

  // ---------------------------------------------------------------------------
  // VIP Cards (Minor Features)
  // ---------------------------------------------------------------------------
  'vipCards': 'VIP Cards',
  'vipCardsDesc': 'Send distinguished cards to your clients',
  'vipCardsSent': 'VIP cards sent successfully',
  'sendCards': 'Send Cards',
  'noVipCards': 'No cards found',

  // ---------------------------------------------------------------------------
  // Attendance (Minor Features)
  // ---------------------------------------------------------------------------
  'attendanceRecord': 'Attendance Record',
  'attendanceNotifications': 'Send attendance and absence notifications to parents',
  'attendanceSent': 'Attendance records sent successfully',
  'attendanceMessageHint': 'Enter attendance message text',
  'sendRecords': 'Send Records',
  'noRecords': 'No records found',
  'statusPresent': 'Present',
  'statusAbsent': 'Absent',
  'statusLate': 'Late',
  'statusExcused': 'Excused',

  // ---------------------------------------------------------------------------
  // Noor Import (Minor Features)
  // ---------------------------------------------------------------------------
  'noorMessages': 'Noor Messages',
  'noorLoginDesc': 'Login to import student data',
  'enterNoorUsername': 'Enter Noor username',
  'selectStudentGroups': 'Select Student Groups',
  'noAvailableGroups': 'No available groups',
  'studentUnit': 'student',
  'enterMessageToSend': 'Enter the message to send',
  'sendMessagesBtn': 'Send Messages',
  'selectAtLeastOneGroup': 'Please select at least one group',
  'noorMessagesSent': 'Noor messages sent successfully',
  'noNoorMessages': 'No Noor messages found',

  // ---------------------------------------------------------------------------
  // Absence (Minor Features)
  // ---------------------------------------------------------------------------
  'absenceType': 'Absence',
  'tardinessType': 'Tardiness',
  'absenceManageDesc': 'Manage absence and tardiness messages sent to parents',
  'resetFilter': 'Filter',

  // ---------------------------------------------------------------------------
  // Message Type Labels
  // ---------------------------------------------------------------------------
  'msg_type_from_numbers': 'Send to Numbers',
  'msg_type_from_numbers_short': 'Numbers',
  'msg_type_from_groups': 'Send to Groups',
  'msg_type_from_groups_short': 'Groups',
  'msg_type_from_noor': 'Noor Messages',
  'msg_type_from_noor_short': 'Noor',
  'msg_type_custom_messages': 'Custom Messages',
  'msg_type_custom_messages_short': 'Custom',
  'msg_type_absence_lateness': 'Absence & Lateness',
  'msg_type_absence_lateness_short': 'Absence',
  'msg_type_teacher_messages': 'Teacher Messages',
  'msg_type_teacher_messages_short': 'Teachers',
  'msg_type_long_messages': 'Long Messages',
  'msg_type_long_messages_short': 'Long',
  'msg_type_voice_messages': 'Voice Messages',
  'msg_type_voice_messages_short': 'Voice',
  'msg_type_file_messages': 'File Messages',
  'msg_type_file_messages_short': 'Files',
  'msg_type_thanks_certifications': 'Thank You Certificates',
  'msg_type_thanks_certifications_short': 'Thanks',
  'msg_type_vip_cards': 'VIP Cards',
  'msg_type_vip_cards_short': 'VIP',
  'msg_type_bulk_messages': 'Bulk Messages',
  'msg_type_bulk_messages_short': 'Bulk',
  'msg_type_attendance_records': 'Attendance Records',
  'msg_type_attendance_records_short': 'Attendance',
  'msg_type_certifications': 'Certifications',
  'msg_type_certifications_short': 'Certs',

  // ---------------------------------------------------------------------------
  // Message Status Labels
  // ---------------------------------------------------------------------------
  'msg_status_sent': 'Sent',
  'msg_status_delivered': 'Delivered',
  'msg_status_pending': 'Pending',
  'msg_status_failed': 'Failed',
  'msg_status_scheduled': 'Scheduled',
  'msg_status_rejected': 'Rejected',
  'msg_status_expired': 'Expired',

  // ---------------------------------------------------------------------------
  // Message Card & Message Center
  // ---------------------------------------------------------------------------
  'msg_recipients_count_tooltip': 'Recipients Count',
  'msg_delivered_tooltip': 'Delivered',
  'msg_failed_tooltip': 'Failed',
  'msg_cost_unit': 'message',
  'msg_time_now': 'Now',
  'msg_time_minutes_ago': '{count} minutes ago',
  'msg_time_hours_ago': '{count} hours ago',
  'msg_time_yesterday': 'Yesterday',
  'msg_time_days_ago': '{count} days ago',
  'msg_tab_all_messages': 'All Messages',
  'msg_tab_pending': 'Pending Messages',
  'msg_tab_attachments': 'Attachments',
  'msg_tab_templates': 'Templates',
  'msg_tab_sender_names': 'Sender Names',
  'msg_tab_short_links': 'Short Links',
  'msg_new_message': 'New Message',
  'msg_advanced_send': 'Advanced Send',
  'msg_export_log': 'Export Log',
  'msg_exporting_log': 'Exporting log...',
  'msg_search_hint': 'General search (by text: message, sender name)',
  'msg_filter_title': 'Filter Messages',
  'msg_filter_sender_name': 'Sender Name',
  'msg_filter_select_sender': 'Select Sender Name',
  'msg_filter_message_type': 'Message Type',
  'msg_filter_with_attachments': 'With Attachments',
  'msg_filter_message_status': 'Message Status',
  'msg_filter_reset': 'Reset Filters',
  'msg_status_chip_all': 'All',
  'msg_status_chip_sent': 'Sent',
  'msg_status_chip_failed': 'Failed',
  'msg_status_chip_pending': 'Pending',
  'msg_load_failed': 'Failed to load messages',
  'msg_no_messages': 'No messages found',
  'msg_start_first': 'Start by sending your first message',

  // ---------------------------------------------------------------------------
  // Messages Pending Tab
  // ---------------------------------------------------------------------------
  'msg_pending_load_failed': 'Failed to load pending messages',
  'msg_no_pending': 'No pending messages',
  'msg_all_processed': 'All messages have been processed',

  // ---------------------------------------------------------------------------
  // Messages Attachments Tab
  // ---------------------------------------------------------------------------
  'msg_attachments_title': 'Attachments',
  'msg_attachments_desc': 'Browse all attachments sent with messages',
  'msg_attachments_placeholder': 'Attachments will appear here when messages are sent with files',

  // ---------------------------------------------------------------------------
  // Template Picker
  // ---------------------------------------------------------------------------
  'msg_select_template': 'Select Template',
  'msg_new_template': 'New',
  'msg_search_template': 'Search templates...',
  'msg_templates_load_failed': 'Failed to load templates',
  'msg_no_matching_results': 'No matching results',
  'msg_no_saved_templates': 'No saved templates',

  // ---------------------------------------------------------------------------
  // Recipient Input
  // ---------------------------------------------------------------------------
  'msg_recipient_numbers': 'Recipient Numbers',
  'msg_number_count': '{count} numbers',
  'msg_number_validation': 'Number must start with 5 and be 9 digits',
  'msg_number_hint': 'Enter a number starting with 5, 9 digits (e.g. 512345678)',
  'msg_clear_all': 'Clear All',

  // ---------------------------------------------------------------------------
  // Message Composer
  // ---------------------------------------------------------------------------
  'msg_message_body_label': 'Message Body',
  'msg_template_btn': 'Template',
  'msg_variable_btn': 'Variable',
  'msg_insert_variable': 'Insert Variable',
  'msg_body_hint': 'Type your message here...',
  'msg_char_label': 'chars',
  'msg_sms_label': 'message',
  'msg_var_student_name': 'Student Name',
  'msg_var_customer_name': 'Customer Name',
  'msg_var_guardian_name': 'Guardian Name',
  'msg_var_teacher_name': 'Teacher Name',
  'msg_var_class_name': 'Class Name',
  'msg_var_school_name': 'School Name',
  'msg_var_date': 'Date',
  'msg_var_time': 'Time',
  'msg_var_grade': 'Grade',
  'msg_var_absence_date': 'Absence Date',
  'msg_var_company_name': 'Company Name',
  'msg_var_order_number': 'Order Number',

  // ---------------------------------------------------------------------------
  // Schedule Picker
  // ---------------------------------------------------------------------------
  'msg_send_time_label': 'Send Time',
  'msg_send_now': 'Send Now',
  'msg_send_later': 'Send Later',
  'msg_pick_date': 'Pick Date',
  'msg_pick_time': 'Pick Time',
  'msg_date_label': 'Date',
  'msg_time_label': 'Time',
  'msg_scheduled_summary': 'Will be sent on {date} at {time}',

  // ---------------------------------------------------------------------------
  // Send Message Screen
  // ---------------------------------------------------------------------------
  'msg_send_success': 'Sent Successfully',
  'msg_send_numbers_count': 'Numbers count: {count}',
  'msg_send_sms_count': 'Messages count: {count}',
  'msg_send_failed': 'Failed to send message',
  'msg_send_failed_title': 'Send Failed',
  'msg_done': 'Done',
  'msg_ok': 'OK',
  'msg_preview_btn': 'Preview',
  'msg_send_btn': 'Send',
  'msg_numbers_tab': 'Numbers',
  'msg_groups_tab': 'Groups',
  'msg_groups_label': 'Groups',
  'msg_group_count': '{count} groups',
  'msg_number_count_label': '{count} numbers',
  'msg_sender_name_label': 'Sender Name',
  'msg_sender_load_failed': 'Failed to load sender names',
  'msg_no_senders': 'No sender names available',
  'msg_select_sender': 'Select Sender Name',
  'msg_groups_load_failed': 'Failed to load groups',
  'msg_reload': 'Reload',
  'msg_no_groups': 'No groups found',
  'msg_total_numbers': '{count} total numbers',
  'msg_search_name_number': 'Search by name or number...',
  'msg_selected_numbers': 'Selected numbers:',
  'msg_save_count': 'Save ({count})',
  'msg_loaded_count': '{count} loaded',
  'msg_preview_title': 'Message Preview',
  'msg_preview_recipients': 'Recipients Count',
  'msg_preview_sms_count': 'SMS Count',
  'msg_preview_cost': 'Estimated Cost',
  'msg_preview_cost_value': '{cost} messages',
  'msg_preview_body': 'Message body:',
  'msg_confirm_send': 'Confirm Send',
  'msg_validate_select_sender': 'Please select a sender name',
  'msg_validate_write_body': 'Please write a message body',
  'msg_validate_add_recipients': 'Please add numbers or select a group',
  'msg_validate_select_datetime': 'Please select a send date and time',
};
