/// Complete English translations for the ORBIT SMS V3 application.
const Map<String, String> en = {
  // ---------------------------------------------------------------------------
  // Common
  // ---------------------------------------------------------------------------
  'appName': 'ORBIT SMS',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Operation completed successfully',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'delete': 'Delete',
  'edit': 'Edit',
  'save': 'Save',
  'search': 'Search',
  'filter': 'Filter',
  'export': 'Export',
  'import': 'Import',
  'refresh': 'Refresh',
  'retry': 'Retry',
  'close': 'Close',
  'back': 'Back',
  'next': 'Next',
  'previous': 'Previous',
  'seeAll': 'See All',
  'noData': 'No data available',
  'noResults': 'No results found',
  'yes': 'Yes',
  'no': 'No',
  'ok': 'OK',
  'done': 'Done',
  'select': 'Select',
  'selectAll': 'Select All',
  'deselectAll': 'Deselect All',
  'copy': 'Copy',
  'copied': 'Copied',
  'share': 'Share',
  'download': 'Download',
  'upload': 'Upload',
  'add': 'Add',
  'remove': 'Remove',
  'apply': 'Apply',
  'reset': 'Reset',
  'submit': 'Submit',
  'continue_': 'Continue',
  'skip': 'Skip',
  'details': 'Details',
  'more': 'More',
  'less': 'Less',
  'all': 'All',
  'active': 'Active',
  'inactive': 'Inactive',
  'enabled': 'Enabled',
  'disabled': 'Disabled',
  'pending': 'Pending',
  'completed': 'Completed',
  'failed': 'Failed',
  'sent': 'Sent',
  'delivered': 'Delivered',
  'rejected': 'Rejected',
  'from': 'From',
  'to': 'To',
  'date': 'Date',
  'time': 'Time',
  'status': 'Status',
  'type': 'Type',
  'count': 'Count',
  'total': 'Total',
  'description': 'Description',
  'note': 'Note',
  'notes': 'Notes',

  // ---------------------------------------------------------------------------
  // Auth
  // ---------------------------------------------------------------------------
  'login': 'Login',
  'register': 'Register',
  'logout': 'Logout',
  'username': 'Username',
  'password': 'Password',
  'currentPassword': 'Current Password',
  'newPassword': 'New Password',
  'confirmPassword': 'Confirm Password',
  'phone': 'Phone Number',
  'email': 'Email',
  'forgotPassword': 'Forgot Password?',
  'resetPassword': 'Reset Password',
  'otpVerification': 'OTP Verification',
  'verify': 'Verify',
  'resendCode': 'Resend Code',
  'codeExpiresIn': 'Code expires in',
  'rememberMe': 'Remember Me',
  'termsAndConditions': 'Terms & Conditions',
  'privacyPolicy': 'Privacy Policy',
  'createAccount': 'Create Account',
  'welcomeBack': 'Welcome Back',
  'signInToContinue': 'Sign in to continue',
  'enterOtpSent': 'Enter the verification code sent to',
  'agreeToTerms': 'By registering you agree to',
  'and': 'and',
  'alreadyHaveAccount': 'Already have an account?',
  'dontHaveAccount': "Don't have an account?",
  'fullName': 'Full Name',
  'companyName': 'Company Name',
  'changePassword': 'Change Password',
  'passwordChanged': 'Password changed successfully',

  // ---------------------------------------------------------------------------
  // Dashboard
  // ---------------------------------------------------------------------------
  'dashboard': 'Dashboard',
  'currentBalance': 'Current Balance',
  'messagesUnit': 'messages',
  'services': 'Services',
  'consumedPoints': 'Consumed Points',
  'viewAllOperations': 'View All Operations',
  'newMessage': 'New Message',
  'advancedSend': 'Advanced Send',
  'groups': 'Groups',
  'subAccounts': 'Sub Accounts',
  'addBalance': 'Add Balance',
  'quickActions': 'Quick Actions',
  'recentOperations': 'Recent Operations',
  'sendingStatistics': 'Sending Statistics',
  'todaySent': 'Sent Today',
  'monthSent': 'Sent This Month',
  'totalSent': 'Total Sent',

  // ---------------------------------------------------------------------------
  // Messages
  // ---------------------------------------------------------------------------
  'messageCenter': 'Message Center',
  'sendMessage': 'Send Message',
  'sendToNumbers': 'Send to Numbers',
  'sendToGroups': 'Send to Groups',
  'senderName': 'Sender Name',
  'messageBody': 'Message Body',
  'sendNow': 'Send Now',
  'schedule': 'Schedule',
  'scheduleMessage': 'Schedule Message',
  'scheduledDate': 'Scheduled Date',
  'scheduledTime': 'Scheduled Time',
  'preview': 'Preview',
  'messageCost': 'Message Cost',
  'recipientsCount': 'Recipients Count',
  'smsCount': 'SMS Count',
  'template': 'Template',
  'selectTemplate': 'Select Template',
  'saveAsTemplate': 'Save as Template',
  'messageType': 'Message Type',
  'characters': 'characters',
  'remainingCharacters': 'Remaining characters',
  'enterNumbers': 'Enter Numbers',
  'numbersHint': 'Enter numbers separated by a new line',
  'selectSenderName': 'Select Sender Name',
  'messagePreview': 'Message Preview',
  'confirmSend': 'Confirm Send',
  'messageSent': 'Message sent successfully',
  'messageScheduled': 'Message scheduled successfully',
  'duplicateNumbers': 'Duplicate numbers',
  'invalidNumbers': 'Invalid numbers',
  'removeDuplicates': 'Remove duplicates',
  'removeInvalid': 'Remove invalid',

  // ---------------------------------------------------------------------------
  // Groups
  // ---------------------------------------------------------------------------
  'createGroup': 'Create Group',
  'editGroup': 'Edit Group',
  'deleteGroup': 'Delete Group',
  'groupName': 'Group Name',
  'numbers': 'Numbers',
  'addNumber': 'Add Number',
  'importExcel': 'Import from Excel',
  'phoneNumber': 'Phone Number',
  'name': 'Name',
  'identifier': 'Identifier',
  'contactsCount': 'Contacts Count',
  'addContact': 'Add Contact',
  'editContact': 'Edit Contact',
  'deleteContact': 'Delete Contact',
  'importContacts': 'Import Contacts',
  'exportContacts': 'Export Contacts',
  'groupCreated': 'Group created successfully',
  'groupUpdated': 'Group updated successfully',
  'groupDeleted': 'Group deleted successfully',
  'contactAdded': 'Contact added successfully',
  'contactUpdated': 'Contact updated successfully',
  'contactDeleted': 'Contact deleted successfully',
  'confirmDeleteGroup': 'Are you sure you want to delete this group?',
  'confirmDeleteContact': 'Are you sure you want to delete this contact?',
  'noGroups': 'No groups found',
  'noContacts': 'No contacts found',
  'searchContacts': 'Search contacts',

  // ---------------------------------------------------------------------------
  // Balance
  // ---------------------------------------------------------------------------
  'balance': 'Balance',
  'buyBalance': 'Buy Balance',
  'transferBalance': 'Transfer Balance',
  'transactionHistory': 'Transaction History',
  'bankTransfer': 'Bank Transfer',
  'onlinePayment': 'Online Payment',
  'stcPay': 'STC Pay',
  'sadad': 'SADAD',
  'amount': 'Amount',
  'pricePerSms': 'Price per SMS',
  'vat': 'VAT',
  'totalAmount': 'Total Amount',
  'paymentMethod': 'Payment Method',
  'paymentSuccess': 'Payment completed successfully',
  'paymentFailed': 'Payment failed',
  'transferTo': 'Transfer to',
  'transferFrom': 'Transfer from',
  'transferAmount': 'Transfer amount',
  'transferSuccess': 'Transfer completed successfully',
  'noTransactions': 'No transactions found',
  'invoiceNumber': 'Invoice Number',
  'balancePackages': 'Balance Packages',
  'customAmount': 'Custom Amount',
  'minimumAmount': 'Minimum amount',
  'maximumAmount': 'Maximum amount',
  'sar': 'SAR',

  // Balance Tabs
  'balanceLog': 'Balance Log',
  'packages': 'Packages',
  'bankInfo': 'Bank Info',
  'upgradeJourney': 'Upgrade Journey',
  'requestContractProof': 'Request Contract Proof',
  'balanceTotal': 'Total',
  'balanceRemaining': 'Remaining',
  'balanceConsumed': 'Consumed',
  'balanceTransferred': 'Transferred',
  'balanceExpiresIn': 'Balance expires in',
  'day': 'day',
  'hour': 'hour',
  'minute': 'minute',
  'second': 'second',
  'availablePackages': 'Available Packages',
  'choosePackage': 'Choose the package that suits your needs',
  'noPackages': 'No packages available',
  'buy': 'Buy',
  'bankInfoTitle': 'Bank Information',
  'bankInfoSubtitle': 'You can transfer to one of the following accounts',
  'noBankInfo': 'No bank information available',
  'accountName': 'Account Name',
  'accountNumber': 'Account Number',
  'transferToSubAccount': 'Transfer balance to sub-account',
  'transferHistory': 'Transfer History',
  'noTransferHistory': 'No previous transfers',
  'currentLevel': 'Your Current Level',
  'progressToNextLevel': 'Progress to Next Level',
  'upgradeLevels': 'Upgrade Levels',
  'current': 'Current',
  'messagesNeeded': 'additional messages to reach level',
  'levelBasic': 'Basic',
  'levelSilver': 'Silver',
  'levelGold': 'Gold',
  'levelPlatinum': 'Platinum',
  'levelDiamond': 'Diamond',
  'exportData': 'Data export coming soon',
  'searchLog': 'Search log...',
  'accepted': 'Accepted',
  'expired': 'Expired',

  // ---------------------------------------------------------------------------
  // Archive
  // ---------------------------------------------------------------------------
  'archive': 'Archive',
  'archivedMessages': 'Archived Messages',
  'sender': 'Sender',
  'recipient': 'Recipient',
  'message': 'Message',
  'filterByDate': 'Filter by Date',
  'filterBySender': 'Filter by Sender',
  'filterByStatus': 'Filter by Status',
  'cancelPending': 'Cancel Pending',
  'restore': 'Restore',
  'startDate': 'Start Date',
  'endDate': 'End Date',
  'noMessages': 'No messages found',
  'messageDetails': 'Message Details',
  'deliveryReport': 'Delivery Report',

  // ---------------------------------------------------------------------------
  // Settings
  // ---------------------------------------------------------------------------
  'settings': 'Settings',
  'profile': 'Profile',
  'roles': 'Roles',
  'permissions': 'Permissions',
  'invoices': 'Invoices',
  'apiKeys': 'API Keys',
  'senderNames': 'Sender Names',
  'contracts': 'Contracts',
  'balanceReminder': 'Balance Reminder',
  'help': 'Help',
  'language': 'Language',
  'arabic': 'Arabic',
  'english': 'English',
  'theme': 'Theme',
  'lightMode': 'Light Mode',
  'darkMode': 'Dark Mode',
  'systemMode': 'System Mode',
  'notifications': 'Notifications',
  'notificationSettings': 'Notification Settings',
  'enableNotifications': 'Enable Notifications',
  'notificationSound': 'Notification Sound',
  'notificationVibration': 'Notification Vibration',
  'about': 'About',
  'version': 'Version',
  'termsOfService': 'Terms of Service',
  'contactUs': 'Contact Us',
  'rateApp': 'Rate App',
  'shareApp': 'Share App',
  'editProfile': 'Edit Profile',
  'profileUpdated': 'Profile updated successfully',
  'deleteAccount': 'Delete Account',
  'confirmLogout': 'Are you sure you want to logout?',
  'confirmDeleteAccount':
      'Are you sure you want to delete your account? This action cannot be undone.',
  'minimumBalanceAlert': 'Alert when balance reaches',
  'addSenderName': 'Add Sender Name',
  'senderNameStatus': 'Sender Name Status',
  'apiKeyGenerated': 'API key generated successfully',
  'generateApiKey': 'Generate API Key',
  'copyApiKey': 'Copy API Key',

  // ---------------------------------------------------------------------------
  // Statistics
  // ---------------------------------------------------------------------------
  'statistics': 'Statistics',
  'absenceLateness': 'Absence & Lateness',
  'customMessages': 'Custom Messages',
  'teacherMessages': 'Teacher Messages',
  'exportReport': 'Export Report',
  'dailyStatistics': 'Daily Statistics',
  'weeklyStatistics': 'Weekly Statistics',
  'monthlyStatistics': 'Monthly Statistics',
  'yearlyStatistics': 'Yearly Statistics',
  'chart': 'Chart',
  'table': 'Table',
  'totalMessages': 'Total Messages',
  'deliveredMessages': 'Delivered Messages',
  'failedMessages': 'Failed Messages',
  'pendingMessages': 'Pending Messages',
  'deliveryRate': 'Delivery Rate',

  // ---------------------------------------------------------------------------
  // Services / Addons
  // ---------------------------------------------------------------------------
  'addons': 'Addons',
  'activate': 'Activate',
  'subscribe': 'Subscribe',
  'annualSubscription': 'Annual Subscription',
  'price': 'Price',
  'recommended': 'Recommended',
  'goToCart': 'Go to Cart',
  'activateNow': 'Activate Now',
  'trial': 'Free Trial',
  'trialDays': 'Trial Days',
  'subscriptionActive': 'Subscription Active',
  'subscriptionExpired': 'Subscription Expired',
  'renewSubscription': 'Renew Subscription',
  'subscriptionExpiresOn': 'Subscription expires on',
  'freeTrialEndsOn': 'Free trial ends on',
  'features': 'Features',
  'serviceDetails': 'Service Details',

  // ---------------------------------------------------------------------------
  // Short Links
  // ---------------------------------------------------------------------------
  'shortLinks': 'Short Links',
  'createShortLink': 'Create Short Link',
  'originalUrl': 'Original URL',
  'shortUrl': 'Short URL',
  'clickCount': 'Click Count',
  'linkCopied': 'Link copied',

  // ---------------------------------------------------------------------------
  // Notifications
  // ---------------------------------------------------------------------------
  'notificationCenter': 'Notification Center',
  'markAsRead': 'Mark as Read',
  'markAllAsRead': 'Mark All as Read',
  'noNotifications': 'No notifications',
  'newNotification': 'New Notification',

  // ---------------------------------------------------------------------------
  // Questionnaires
  // ---------------------------------------------------------------------------
  'questionnaires': 'Questionnaires',
  'createQuestionnaire': 'Create Questionnaire',
  'questionnaireTitle': 'Questionnaire Title',
  'questions': 'Questions',
  'addQuestion': 'Add Question',
  'responses': 'Responses',
  'responseCount': 'Response Count',

  // ---------------------------------------------------------------------------
  // Occasion Cards
  // ---------------------------------------------------------------------------
  'occasionCards': 'Occasion Cards',
  'createCard': 'Create Card',
  'selectOccasion': 'Select Occasion',
  'cardTemplate': 'Card Template',
  'customizeCard': 'Customize Card',
  'sendCard': 'Send Card',

  // ---------------------------------------------------------------------------
  // Contact Me
  // ---------------------------------------------------------------------------
  'contactMe': 'Contact Me',
  'contactForm': 'Contact Form',
  'yourMessage': 'Your Message',
  'sendRequest': 'Send Request',
  'requestSent': 'Your request has been sent successfully',

  // ---------------------------------------------------------------------------
  // Interaction
  // ---------------------------------------------------------------------------
  'interaction': 'Interaction',
  'interactionReports': 'Interaction Reports',
  'interactionRate': 'Interaction Rate',

  // ---------------------------------------------------------------------------
  // Files
  // ---------------------------------------------------------------------------
  'files': 'Files',
  'uploadFile': 'Upload File',
  'fileSize': 'File Size',
  'fileType': 'File Type',
  'fileName': 'File Name',
  'downloadFile': 'Download File',
  'deleteFile': 'Delete File',
  'noFiles': 'No files found',

  // ---------------------------------------------------------------------------
  // Certifications
  // ---------------------------------------------------------------------------
  'certifications': 'Certifications',
  'createCertification': 'Create Certification',
  'certificationTemplate': 'Certification Template',
  'recipientName': 'Recipient Name',
  'issuedDate': 'Issued Date',
  'downloadCertification': 'Download Certification',

  // ---------------------------------------------------------------------------
  // Validation Messages
  // ---------------------------------------------------------------------------
  'requiredField': 'This field is required',
  'invalidEmail': 'Invalid email address',
  'invalidPhone': 'Invalid phone number',
  'passwordTooShort': 'Password is too short (minimum 8 characters)',
  'passwordsDontMatch': 'Passwords do not match',
  'minLength': 'Minimum length is {min} characters',
  'maxLength': 'Maximum length is {max} characters',
  'invalidUsername': 'Invalid username',
  'invalidNumber': 'Please enter a valid number',
  'passwordRequirements':
      'Password must contain an uppercase letter, a lowercase letter, a number, and a special character',

  // ---------------------------------------------------------------------------
  // Error Messages
  // ---------------------------------------------------------------------------
  'networkError': 'Network error. Please check your internet connection.',
  'serverError': 'Server error. Please try again later.',
  'sessionExpired': 'Session Expired',
  'pleaseLoginAgain': 'Please login again',
  'unknownError': 'An unknown error occurred',
  'tryAgain': 'Try Again',
  'connectionTimeout': 'Connection timed out',
  'unauthorizedAccess': 'Unauthorized access',
  'forbidden': 'You do not have permission to access this',
  'notFound': 'Not found',
  'tooManyRequests': 'Too many requests. Please try again later.',
  'maintenanceMode': 'App is under maintenance. Please try again later.',

  // ---------------------------------------------------------------------------
  // Navigation
  // ---------------------------------------------------------------------------
  'home': 'Home',
  'messages': 'Messages',
  // 'groups' is already defined above
  // 'balance' is already defined above
  // 'more' is already defined above

  // ---------------------------------------------------------------------------
  // Time / Date
  // ---------------------------------------------------------------------------
  'today': 'Today',
  'yesterday': 'Yesterday',
  'daysAgo': '{count} days ago',
  'hoursAgo': '{count} hours ago',
  'minutesAgo': '{count} minutes ago',
  'justNow': 'Just now',
  'seconds': 'seconds',
  'minutes': 'minutes',
  'hours': 'hours',
  'days': 'days',

  // ---------------------------------------------------------------------------
  // Absence Messages
  // ---------------------------------------------------------------------------
  'absenceMessages': 'Absence & Tardiness Messages',
  'absenceMessagesDescription': 'Manage absence and tardiness messages sent to parents/guardians',
  'sendAbsenceMessage': 'Send Absence Message',
  'absence': 'Absence',
  'tardiness': 'Tardiness',
  'senderNameFilter': 'Sender Name',
  'messageTypeFilter': 'Message Type',
  'messageClassification': 'Message Classification',
  'hijriDate': 'Hijri Date',
  'fromDate': 'From Date',
  'toDate': 'To Date',
  'selectSender': 'Select Sender',
  'selectType': 'Select Type',
  'selectClassification': 'Select Classification',
  'allMessages': 'All',
  'sentMessages': 'Sent',
  'failedMessages_': 'Failed',
  'pendingMessages_': 'Pending',
  'sendTime': 'Send Time',
  'receiveTime': 'Receive Time',
  'recipientCountLabel': 'Recipients Count',
  'statusAccepted': 'Accepted',
  'statusRejected': 'Rejected',
  'statusExpired': 'Expired',
  'statusUnderReview': 'Under Review',
  'view': 'View',
  'report': 'Report',
  'searchAbsenceMessages': 'Search absence & tardiness messages...',
  'noAbsenceMessages': 'No messages found',

  // ---------------------------------------------------------------------------
  // Statements & Responses
  // ---------------------------------------------------------------------------
  'statements': 'Statements & Responses',
  'statementsDescription': 'View user responses to sent messages.',
  'exportResponses': 'Export Responses',
  'responseText': 'Response Text',
  'senderAccount': 'Sender Account',
  'responseTime': 'Response Time',
  'attachmentLabel': 'Attachment',
  'shortStatements': 'Short',
  'voiceStatements': 'Voice',
  'longStatements': 'Long',
  'unregisteredNumbers': 'Unregistered Numbers',
  'absenceAndTardiness': 'Absence & Tardiness',
  'generalSearch': 'General Search',
  'generalSearchHint': 'Search by text: message, sender name',
  'groupFilter': 'Group',
  'noResponses': 'No responses found',
  'deleteResponse': 'Delete Response',
  'confirmDeleteResponse': 'Are you sure you want to delete this response?',
  'responseDeleted': 'Response deleted successfully',
  'exportRequested': 'Export request submitted successfully',
  'viewMessageAction': 'View Message',
  'originalMessage': 'Original Message',
  'downloadAttachment': 'Download Attachment',
  'filterStatements': 'Filter Statements',
  'searchStatements': 'Search statements & responses...',

  // ---------------------------------------------------------------------------
  // More Screen Sections & Help
  // ---------------------------------------------------------------------------
  'messagesSection': 'Messages',
  'messageTools': 'Message Tools',
  'servicesAndStatistics': 'Services & Statistics',
  'account': 'Account',
  'helpSection': 'Help',
  'environmentRules': 'Message Environment Rules',
  'userGuide': 'User Guide',
  'reportProblem': 'Report a Problem',
  'helpAndSupport': 'Help & Support',

  // ---------------------------------------------------------------------------
  // Miscellaneous
  // ---------------------------------------------------------------------------
  'welcomeMessage': 'Welcome to ORBIT SMS',
  'onboardingTitle1': 'Send Bulk Messages',
  'onboardingDesc1':
      'Send your messages to thousands of numbers with a single tap',
  'onboardingTitle2': 'Manage Contacts',
  'onboardingDesc2':
      'Organize your contacts into groups for easy messaging',
  'onboardingTitle3': 'Track & Statistics',
  'onboardingDesc3':
      'Follow your message status and sending statistics in detail',
  'getStarted': 'Get Started',
  'poweredBy': 'Powered by ORBIT',
  'copyright': 'All rights reserved',
};
